<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>إدارة خدمات {{ $shop->name }}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">@include('admin.real_estate.modular._styles')</head><body>@include('admin.includes.sidebar')<main class="modular-page">
@if(session('status'))<div class="success-box">{{ session('status') }}</div>@endif
<section class="hero glass"><div class="hero-top"><div><span class="eyebrow">MODULAR SERVICES CONTROL</span><h1>إدارة خدمات {{ $shop->name }}</h1><p>أقسام البناء المتنقل والخدمات والمواصفات وطلبات واتساب في مكان واحد.</p></div><div class="actions"><a class="btn" target="_blank" href="{{ route('real-estate.company', $shop) }}"><i class="ti ti-external-link"></i> صفحة الشركة</a><a class="btn" href="{{ route('real-estate.dashboard.categories.create', $shop) }}"><i class="ti ti-category-plus"></i> قسم جديد</a><a class="btn btn-primary" href="{{ route('real-estate.dashboard.services.create', $shop) }}"><i class="ti ti-plus"></i> خدمة جديدة</a></div></div></section>
<section class="stats">@foreach([['الأقسام',$stats['categories'],'ti-category'],['الخدمات',$stats['services'],'ti-building-community'],['مجموع قوائم الخيارات',$stats['options'],'ti-adjustments'],['طلبات جديدة',$stats['new_requests'],'ti-brand-whatsapp']] as $stat)<article class="stat glass"><small><i class="ti {{ $stat[2] }}"></i> {{ $stat[0] }}</small><strong>{{ $stat[1] }}</strong></article>@endforeach</section>
<section class="section glass"><div class="section-head"><div><h2>الأقسام والخدمات</h2><span class="muted">كل خدمة تحتوي على قوائم المقاسات والمواد والتجهيزات الخاصة بها.</span></div><a class="btn btn-primary" href="{{ route('real-estate.dashboard.services.create', $shop) }}"><i class="ti ti-plus"></i> إضافة خدمة</a></div><div class="categories">
@forelse($categories as $category)<article class="category glass"><header class="category-head">@if($category->imageUrl())<img src="{{ $category->imageUrl() }}" alt="">@endif<div class="category-copy"><h3>{{ $category->name }}</h3><small>{{ $category->services->count() }} خدمات · {{ $category->is_active ? 'ظاهر' : 'مخفي' }}</small></div><div class="actions"><a class="btn" href="{{ route('real-estate.dashboard.categories.edit', [$shop, $category]) }}"><i class="ti ti-edit"></i></a><a class="btn" href="{{ route('real-estate.dashboard.services.create', [$shop, 'category' => $category->id]) }}"><i class="ti ti-plus"></i></a><form method="post" action="{{ route('real-estate.dashboard.categories.destroy', [$shop, $category]) }}">@csrf @method('delete')<button class="btn btn-danger" onclick="return confirm('حذف القسم وجميع خدماته وطلباته؟')"><i class="ti ti-trash"></i></button></form></div></header><div class="service-list">
@forelse($category->services as $service)<div class="service-row">@if($service->imageUrl())<img src="{{ $service->imageUrl() }}" alt="">@endif<div class="service-info"><b>{{ $service->name }}</b><small>{{ $service->option_groups_count }} مجموعات خيارات · {{ $service->requests_count }} طلبات · {{ $service->is_active ? 'ظاهر' : 'مخفي' }}</small></div><a class="btn" href="{{ route('real-estate.dashboard.services.edit', [$shop, $service]) }}"><i class="ti ti-settings"></i></a><form method="post" action="{{ route('real-estate.dashboard.services.destroy', [$shop, $service]) }}">@csrf @method('delete')<button class="btn btn-danger" onclick="return confirm('حذف الخدمة وطلباتها؟')"><i class="ti ti-trash"></i></button></form></div>@empty<div class="empty">لا توجد خدمات في هذا القسم.</div>@endforelse
</div></article>@empty<div class="empty">لا توجد أقسام. أضف أول قسم لبدء العمل.</div>@endforelse
</div></section>
<section class="section glass"><div class="section-head"><div><h2><i class="ti ti-brand-whatsapp" style="color:var(--green)"></i> طلبات المواصفات</h2><span class="muted">نسخة من الطلبات التي فتحها العملاء في واتساب الشركة.</span></div></div><div class="table-wrap"><table><thead><tr><th>العميل</th><th>الخدمة</th><th>المواصفات</th><th>ملاحظات</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>
@forelse($serviceRequests as $requestItem)<tr><td data-label="العميل"><b>{{ $requestItem->customer_name }}</b><br><a href="tel:{{ $requestItem->customer_phone }}">{{ $requestItem->customer_phone }}</a><br><small class="muted">{{ $requestItem->city }}</small></td><td data-label="الخدمة"><b>{{ $requestItem->service?->name }}</b><br><small class="muted">{{ $requestItem->service?->category?->name }}</small></td><td data-label="المواصفات"><div class="request-options">@foreach($requestItem->selections ?? [] as $selection)<span class="chip">{{ $selection['group_name'] ?? '' }}: {{ $selection['value_name'] ?? '' }}</span>@endforeach</div></td><td data-label="ملاحظات">{{ $requestItem->notes ?: '—' }}</td><td data-label="التاريخ">{{ $requestItem->created_at->format('Y-m-d H:i') }}</td><td data-label="الحالة"><form class="inline" method="post" action="{{ route('real-estate.dashboard.service-requests.update', [$shop, $requestItem]) }}">@csrf @method('patch')<select class="status-select" name="status">@foreach(['new'=>'جديد','contacted'=>'تم التواصل','completed'=>'مكتمل','cancelled'=>'ملغي'] as $value=>$label)<option value="{{ $value }}" @selected($requestItem->status === $value)>{{ $label }}</option>@endforeach</select><button class="btn" type="submit"><i class="ti ti-device-floppy"></i></button></form></td></tr>@empty<tr><td colspan="6" class="empty">لا توجد طلبات حتى الآن.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $serviceRequests->links() }}</div></section>
</main></body></html>
