@php
    $editing = $service->exists;
    $savedGroups = $editing
        ? $service->optionGroups->map(fn ($group) => [
            'name' => $group->name,
            'name_he' => $group->name_translations['he'] ?? '',
            'name_en' => $group->name_translations['en'] ?? '',
            'help_text' => $group->help_text,
            'help_text_he' => $group->help_text_translations['he'] ?? '',
            'help_text_en' => $group->help_text_translations['en'] ?? '',
            'is_required' => $group->is_required ? 1 : 0,
            'values' => $group->values->map(fn ($value) => [
                'name' => $value->name,
                'name_he' => $value->name_translations['he'] ?? '',
                'name_en' => $value->name_translations['en'] ?? '',
                'is_default' => $value->is_default ? 1 : 0,
            ])->values()->all(),
        ])->values()->all()
        : [['name' => 'المقاس', 'name_he' => '', 'name_en' => 'Size', 'help_text' => 'اختر المقاس المناسب.', 'help_text_he' => '', 'help_text_en' => '', 'is_required' => 1, 'values' => [['name' => 'مقاس حسب الطلب', 'name_he' => '', 'name_en' => 'Custom size', 'is_default' => 1]]]];
    $formGroups = old('option_groups', $savedGroups);
@endphp
<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $editing ? 'تعديل الخدمة' : 'خدمة جديدة' }} | {{ $shop->name }}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">@include('admin.real_estate.modular._styles')</head><body>@include('admin.includes.sidebar')<main class="modular-page">
@if(session('status'))<div class="success-box">{{ session('status') }}</div>@endif
<section class="hero glass"><div class="hero-top"><div><span class="eyebrow">MODULAR SERVICE BUILDER</span><h1>{{ $editing ? 'تعديل '.$service->name : 'إضافة خدمة جديدة' }}</h1><p>أضف صور الخدمة وكل قوائم الخيارات التي سيختار منها العميل قبل إرسال الطلب إلى واتساب.</p></div><div class="actions"><a class="btn" href="{{ route('real-estate.dashboard', $shop) }}"><i class="ti ti-arrow-right"></i> رجوع</a>@if($editing)<a class="btn" target="_blank" href="{{ $service->publicUrl() }}"><i class="ti ti-eye"></i> معاينة</a>@endif</div></div></section>
@if($errors->any())<div class="error-box"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="service-form" method="post" enctype="multipart/form-data" action="{{ $editing ? route('real-estate.dashboard.services.update', [$shop, $service]) : route('real-estate.dashboard.services.store', $shop) }}">@csrf @if($editing)@method('put')@endif
<section class="form-section glass"><h2>بيانات الخدمة</h2><div class="form-grid"><label class="field"><span>القسم *</span><select class="control" name="modular_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('modular_category_id', $selectedCategoryId) === $category->id)>{{ $category->name }}</option>@endforeach</select></label><label class="field"><span>الرابط المختصر (اختياري)</span><input class="control" name="slug" value="{{ old('slug', $service->slug) }}" dir="ltr"></label><label class="field"><span>اسم الخدمة بالعربية *</span><input class="control" name="name" value="{{ old('name', $service->name) }}" required></label><label class="field"><span>الاسم بالعبرية</span><input class="control" name="name_he" value="{{ old('name_he', $service->name_translations['he'] ?? '') }}"></label><label class="field"><span>الاسم بالإنجليزية</span><input class="control" name="name_en" value="{{ old('name_en', $service->name_translations['en'] ?? '') }}" dir="ltr"></label><label class="field"><span>ترتيب الظهور</span><input class="control" type="number" min="0" name="position" value="{{ old('position', $service->position) }}"></label><label class="field full"><span>وصف مختصر بالعربية</span><textarea class="control" name="short_description">{{ old('short_description', $service->short_description) }}</textarea></label><label class="field"><span>الوصف المختصر بالعبرية</span><textarea class="control" name="short_description_he">{{ old('short_description_he', $service->short_description_translations['he'] ?? '') }}</textarea></label><label class="field"><span>الوصف المختصر بالإنجليزية</span><textarea class="control" name="short_description_en" dir="ltr">{{ old('short_description_en', $service->short_description_translations['en'] ?? '') }}</textarea></label><label class="field full"><span>تفاصيل الخدمة بالعربية</span><textarea class="control" name="description">{{ old('description', $service->description) }}</textarea></label><label class="field"><span>التفاصيل بالعبرية</span><textarea class="control" name="description_he">{{ old('description_he', $service->description_translations['he'] ?? '') }}</textarea></label><label class="field"><span>التفاصيل بالإنجليزية</span><textarea class="control" name="description_en" dir="ltr">{{ old('description_en', $service->description_translations['en'] ?? '') }}</textarea></label><label class="check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $editing ? $service->is_active : true))><span>الخدمة ظاهرة للزوار</span></label><label class="check"><input type="hidden" name="is_featured" value="0"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $service->is_featured))><span>خدمة مميزة</span></label></div></section>
<section class="form-section glass"><h2>صور الخدمة</h2><div class="form-grid"><label class="field"><span>صورة الغلاف الرئيسية</span>@if($service->imageUrl())<img class="image-preview" src="{{ $service->imageUrl() }}" alt="">@endif<input class="control" type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"></label><label class="field"><span>صور إضافية (حتى 12 صورة)</span><input class="control" type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple></label></div>@if($editing && $service->images->isNotEmpty())<div class="existing-images">@foreach($service->images as $image)<div class="existing-image"><img src="{{ str_starts_with($image->path, 'images/') ? asset($image->path) : Storage::url($image->path) }}" alt=""><button class="icon-btn danger" type="submit" form="delete-image-{{ $image->id }}" onclick="return confirm('حذف الصورة؟')"><i class="ti ti-trash"></i></button></div>@endforeach</div>@endif</section>
<section class="form-section glass"><div class="section-head"><div><h2>قوائم اختيار المواصفات</h2><span class="muted">مثال: نوع البلاط ← سيراميك كامل / مناطق مبللة / بدون سيراميك.</span></div><button class="btn btn-primary" type="button" id="add-group"><i class="ti ti-plus"></i> إضافة قائمة اختيار</button></div><div class="option-groups" id="option-groups">
@foreach($formGroups as $groupIndex => $group)<article class="option-group" data-group-index="{{ $groupIndex }}"><div class="group-head"><strong>قائمة اختيار</strong><button class="icon-btn danger remove-group" type="button" title="حذف القائمة"><i class="ti ti-trash"></i></button></div><div class="form-grid"><label class="field"><span>اسم القائمة بالعربية *</span><input class="control" name="option_groups[{{ $groupIndex }}][name]" value="{{ $group['name'] ?? '' }}" required></label><label class="field"><span>الاسم بالعبرية</span><input class="control" name="option_groups[{{ $groupIndex }}][name_he]" value="{{ $group['name_he'] ?? '' }}"></label><label class="field"><span>الاسم بالإنجليزية</span><input class="control" name="option_groups[{{ $groupIndex }}][name_en]" value="{{ $group['name_en'] ?? '' }}" dir="ltr"></label><label class="field"><span>شرح قصير للعميل</span><input class="control" name="option_groups[{{ $groupIndex }}][help_text]" value="{{ $group['help_text'] ?? '' }}"></label><label class="field"><span>الشرح بالعبرية</span><input class="control" name="option_groups[{{ $groupIndex }}][help_text_he]" value="{{ $group['help_text_he'] ?? '' }}"></label><label class="field"><span>الشرح بالإنجليزية</span><input class="control" name="option_groups[{{ $groupIndex }}][help_text_en]" value="{{ $group['help_text_en'] ?? '' }}" dir="ltr"></label><label class="check full"><input type="hidden" name="option_groups[{{ $groupIndex }}][is_required]" value="0"><input type="checkbox" name="option_groups[{{ $groupIndex }}][is_required]" value="1" @checked((bool) ($group['is_required'] ?? true))><span>هذا الاختيار مطلوب من العميل</span></label></div><div class="option-values">
@foreach($group['values'] ?? [] as $valueIndex => $value)<div class="value-row"><input class="control" name="option_groups[{{ $groupIndex }}][values][{{ $valueIndex }}][name]" value="{{ $value['name'] ?? '' }}" placeholder="الخيار بالعربية" required><input class="control" name="option_groups[{{ $groupIndex }}][values][{{ $valueIndex }}][name_he]" value="{{ $value['name_he'] ?? '' }}" placeholder="العبرية"><input class="control" name="option_groups[{{ $groupIndex }}][values][{{ $valueIndex }}][name_en]" value="{{ $value['name_en'] ?? '' }}" placeholder="English" dir="ltr"><label class="check"><input type="hidden" name="option_groups[{{ $groupIndex }}][values][{{ $valueIndex }}][is_default]" value="0"><input type="checkbox" name="option_groups[{{ $groupIndex }}][values][{{ $valueIndex }}][is_default]" value="1" @checked((bool) ($value['is_default'] ?? false))><span>افتراضي</span></label><button class="icon-btn danger remove-value" type="button"><i class="ti ti-x"></i></button></div>@endforeach
</div><button class="btn add-value" type="button" style="margin-top:10px"><i class="ti ti-plus"></i> إضافة خيار</button></article>@endforeach
</div></section><div class="sticky-save"><button class="btn btn-primary" type="submit"><i class="ti ti-device-floppy"></i> {{ $editing ? 'حفظ الخدمة والمواصفات' : 'إضافة الخدمة والمواصفات' }}</button></div></form>
@if($editing)@foreach($service->images as $image)<form id="delete-image-{{ $image->id }}" method="post" action="{{ route('real-estate.dashboard.service-images.destroy', [$shop, $image]) }}">@csrf @method('delete')</form>@endforeach @endif
</main>
<script>
(function(){const groups=document.getElementById('option-groups');let counter=Date.now();
function valueHtml(g,v){return `<div class="value-row"><input class="control" name="option_groups[${g}][values][${v}][name]" placeholder="الخيار بالعربية" required><input class="control" name="option_groups[${g}][values][${v}][name_he]" placeholder="العبرية"><input class="control" name="option_groups[${g}][values][${v}][name_en]" placeholder="English" dir="ltr"><label class="check"><input type="hidden" name="option_groups[${g}][values][${v}][is_default]" value="0"><input type="checkbox" name="option_groups[${g}][values][${v}][is_default]" value="1"><span>افتراضي</span></label><button class="icon-btn danger remove-value" type="button"><i class="ti ti-x"></i></button></div>`}
function groupHtml(g){return `<article class="option-group" data-group-index="${g}"><div class="group-head"><strong>قائمة اختيار جديدة</strong><button class="icon-btn danger remove-group" type="button"><i class="ti ti-trash"></i></button></div><div class="form-grid"><label class="field"><span>اسم القائمة بالعربية *</span><input class="control" name="option_groups[${g}][name]" required></label><label class="field"><span>الاسم بالعبرية</span><input class="control" name="option_groups[${g}][name_he]"></label><label class="field"><span>الاسم بالإنجليزية</span><input class="control" name="option_groups[${g}][name_en]" dir="ltr"></label><label class="field"><span>شرح قصير للعميل</span><input class="control" name="option_groups[${g}][help_text]"></label><label class="field"><span>الشرح بالعبرية</span><input class="control" name="option_groups[${g}][help_text_he]"></label><label class="field"><span>الشرح بالإنجليزية</span><input class="control" name="option_groups[${g}][help_text_en]" dir="ltr"></label><label class="check full"><input type="hidden" name="option_groups[${g}][is_required]" value="0"><input type="checkbox" name="option_groups[${g}][is_required]" value="1" checked><span>هذا الاختيار مطلوب من العميل</span></label></div><div class="option-values">${valueHtml(g,++counter)}</div><button class="btn add-value" type="button" style="margin-top:10px"><i class="ti ti-plus"></i> إضافة خيار</button></article>`}
document.getElementById('add-group').addEventListener('click',()=>groups.insertAdjacentHTML('beforeend',groupHtml(++counter)));
groups.addEventListener('click',function(event){const removeGroup=event.target.closest('.remove-group');if(removeGroup){if(groups.querySelectorAll('.option-group').length===1){alert('يجب أن تحتوي الخدمة على قائمة اختيار واحدة على الأقل.');return}removeGroup.closest('.option-group').remove();return}const removeValue=event.target.closest('.remove-value');if(removeValue){const box=removeValue.closest('.option-values');if(box.querySelectorAll('.value-row').length===1){alert('يجب أن تحتوي القائمة على خيار واحد على الأقل.');return}removeValue.closest('.value-row').remove();return}const addValue=event.target.closest('.add-value');if(addValue){const group=addValue.closest('.option-group');group.querySelector('.option-values').insertAdjacentHTML('beforeend',valueHtml(group.dataset.groupIndex,++counter))}});
})();
</script></body></html>
