<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $shop->name }}</title><style>
*{box-sizing:border-box}body{margin:0;background:#090b0d;color:#fff;font-family:Arial,sans-serif}.hero{padding:28px;text-align:center;background:#12181c}.hero img{width:90px;height:90px;border-radius:50%;object-fit:cover}.wrap{max-width:1100px;margin:auto;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.meal,.cart{background:#12171b;border:1px solid #29343b;border-radius:18px;padding:15px}.meal img{width:100%;height:160px;object-fit:cover;border-radius:13px}button,input,select,textarea{width:100%;padding:11px;border-radius:10px;border:1px solid #35434b;background:#0b1014;color:#fff;margin-top:7px}button{background:#00dcef;color:#001014;font-weight:bold}.cart{position:sticky;bottom:0;margin-top:20px;border-color:#00dcef}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hidden{display:none}.item{padding:8px;border-bottom:1px solid #29343b}.ok{color:#59f2a2;font-weight:bold}@media(max-width:600px){.wrap{padding:10px}.row{grid-template-columns:1fr}}
</style></head><body><header class="hero">@if($shop->logo)<img src="{{ asset($shop->logo) }}">@endif<h1>{{ $shop->name }}</h1>@if($table)<p class="ok">الطلب من {{ $table->name }}</p>@else<p>توصيل أو استلام من المطعم</p>@endif</header><main class="wrap"><div class="grid">
@foreach($products as $p)@php($a=$p->catalog_attributes??[])<article class="meal" data-product='@json(["id"=>$p->id,"name"=>$p->name,"price"=>(float)($p->discount_price?:$p->price),"sizes"=>$a["meal_size_prices"]??[],"addons"=>$a["addon_prices"]??[],"ingredients"=>preg_split("/[,،\\n]+/",$a["ingredients"]??"",-1,PREG_SPLIT_NO_EMPTY)])'>@if($p->main_image)<img src="{{ asset($p->main_image) }}">@endif<h3>{{ $p->name }}</h3><p>{{ $p->description }}</p><b>{{ $p->discount_price ?: $p->price }} ₪</b><button class="add">تخصيص وإضافة</button></article>@endforeach
</div><section class="cart"><h2>طلبك</h2><div id="items">السلة فارغة</div><b>المجموع: <span id="total">0.00</span> ₪</b>
<div class="row">@unless($table)<select id="type"><option value="delivery">توصيل</option><option value="pickup">استلام من المطعم</option></select>@else<input type="hidden" id="type" value="dine_in">@endunless<input id="name" placeholder="الاسم" required></div><div class="row"><input id="phone" placeholder="رقم الهاتف"><input id="address" placeholder="عنوان التوصيل"></div><textarea id="orderNotes" placeholder="ملاحظات عامة"></textarea><button id="send">إرسال الطلب</button><p id="message"></p></section></main>
<dialog id="modal" style="background:#12171b;color:#fff;border:1px solid #00dcef;border-radius:18px;max-width:430px;width:90%"><h3 id="mname"></h3><label>الحجم<select id="size"></select></label><div id="addons"></div><div id="excluded"></div><textarea id="notes" placeholder="ملاحظات على الوجبة"></textarea><input id="qty" type="number" min="1" value="1"><button id="confirm">إضافة للسلة</button><button onclick="modal.close()" style="background:#333;color:#fff">إلغاء</button></dialog>
<script>
const cart=[];let current=null;const parse=v=>Object.fromEntries(v.map(x=>{let [n,p]=x.split(':');return[n.trim(),Number(p)||0]}));
document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{current=JSON.parse(b.closest('.meal').dataset.product);mname.textContent=current.name;let sizes=parse(current.sizes),adds=parse(current.addons);size.innerHTML='<option value="">السعر الأساسي</option>'+Object.entries(sizes).map(([n,p])=>`<option value="${n}" data-price="${p}">${n} - ${p} ₪</option>`).join('');addons.innerHTML='<h4>الإضافات</h4>'+Object.entries(adds).map(([n,p])=>`<label><input type="checkbox" value="${n}" data-price="${p}"> ${n} (+${p})</label>`).join('');excluded.innerHTML='<h4>حذف مكونات</h4>'+current.ingredients.map(n=>`<label><input type="checkbox" value="${n}"> بدون ${n}</label>`).join('');modal.showModal()});
confirm.onclick=()=>{let s=size.selectedOptions[0],base=s?.dataset.price?Number(s.dataset.price):current.price,ad=[...addons.querySelectorAll(':checked')],unit=base+ad.reduce((x,e)=>x+Number(e.dataset.price),0);cart.push({product_id:current.id,name:current.name,qty:Number(qty.value),size:size.value,addons:ad.map(e=>e.value),excluded:[...excluded.querySelectorAll(':checked')].map(e=>e.value),notes:notes.value,unit});modal.close();render()};
function render(){items.innerHTML=cart.map((x,i)=>`<div class=item>${x.qty}× ${x.name} ${x.size}<button onclick="cart.splice(${i},1);render()">حذف</button></div>`).join('')||'السلة فارغة';total.textContent=cart.reduce((s,x)=>s+x.unit*x.qty,0).toFixed(2)}
send.onclick=async()=>{message.textContent='';let payload={order_type:type.value,table_code:@json($table?->code),customer_name:name.value,customer_phone:phone.value,customer_address:address.value,customer_notes:orderNotes.value,items:cart};let r=await fetch(@json(route('restaurant.orders.store',$shop)),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok){message.textContent=j.message||'تحقق من البيانات';return}cart.length=0;render();message.className='ok';message.textContent='تم إرسال الطلب: '+j.order_number}
</script></body></html>
