<?php

return [
    'general' => [
        'label' => 'متجر عام',
        'description' => 'منتجات عامة بدون خصائص متخصصة.',
        'suggested_categories' => ['الأكثر مبيعًا', 'وصل حديثًا', 'عروض', 'منتجات متنوعة'],
        'icon' => 'ti-building-store',
        'fields' => [
            'brand' => ['label' => 'العلامة التجارية', 'type' => 'text'],
            'model' => ['label' => 'الموديل أو الإصدار', 'type' => 'text'],
            'unit' => ['label' => 'وحدة البيع', 'type' => 'select', 'options' => ['قطعة', 'عبوة', 'كرتونة', 'كيلوغرام', 'لتر']],
        ],
    ],
    'clothing' => [
        'label' => 'ملابس وأزياء',
        'description' => 'مقاسات، ألوان، خامات، جنس وموسم.',
        'suggested_categories' => ['رجالي', 'نسائي', 'أطفال', 'قمصان', 'بناطيل', 'فساتين', 'جاكيتات', 'إكسسوارات'],
        'icon' => 'ti-shirt',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'gender' => ['label' => 'الفئة', 'type' => 'select', 'options' => ['رجالي', 'نسائي', 'أطفال', 'يونيسكس']],
            'sizes' => ['label' => 'المقاسات المتوفرة', 'type' => 'list', 'placeholder' => 'مثال: S, M, L, XL'],
            'colors' => ['label' => 'الألوان المتوفرة', 'type' => 'list', 'placeholder' => 'مثال: أسود, أبيض, أزرق'],
            'material' => ['label' => 'الخامة أو القماش', 'type' => 'text'],
            'season' => ['label' => 'الموسم', 'type' => 'select', 'options' => ['صيفي', 'شتوي', 'كل المواسم']],
            'care' => ['label' => 'تعليمات الغسيل والعناية', 'type' => 'textarea'],
        ],
    ],
    'shoes' => [
        'label' => 'أحذية',
        'description' => 'مقاسات أحذية، ألوان، خامة ونوع استخدام.',
        'suggested_categories' => ['رجالي', 'نسائي', 'أطفال', 'رياضي', 'رسمي', 'صنادل', 'أحذية عمل'],
        'icon' => 'ti-shoe',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'gender' => ['label' => 'الفئة', 'type' => 'select', 'options' => ['رجالي', 'نسائي', 'أطفال', 'يونيسكس']],
            'sizes' => ['label' => 'النمر أو المقاسات', 'type' => 'list', 'placeholder' => 'مثال: 36, 37, 38, 39'],
            'colors' => ['label' => 'الألوان المتوفرة', 'type' => 'list'],
            'material' => ['label' => 'الخامة', 'type' => 'text'],
            'shoe_use' => ['label' => 'الاستخدام', 'type' => 'select', 'options' => ['رياضي', 'رسمي', 'يومي', 'منزلي', 'عمل']],
        ],
    ],
    'sweets' => [
        'label' => 'حلويات ومخبوزات',
        'description' => 'نكهات، وزن، عدد القطع، مناسبة وحساسيات.',
        'suggested_categories' => ['كيك', 'حلويات شرقية', 'حلويات غربية', 'شوكولاتة', 'مخبوزات', 'ضيافة', 'مناسبات'],
        'icon' => 'ti-cake',
        'fields' => [
            'sweet_type' => ['label' => 'نوع الحلوى', 'type' => 'text'],
            'flavors' => ['label' => 'النكهات المتوفرة', 'type' => 'list'],
            'weight' => ['label' => 'الوزن أو الحجم', 'type' => 'text', 'placeholder' => 'مثال: 500 غرام'],
            'pieces' => ['label' => 'عدد القطع', 'type' => 'number'],
            'occasion' => ['label' => 'المناسبة', 'type' => 'select', 'options' => ['يومي', 'أعياد ميلاد', 'أعراس', 'ضيافة', 'مناسبات']],
            'allergens' => ['label' => 'مسببات الحساسية', 'type' => 'list', 'placeholder' => 'مثال: مكسرات, حليب, جلوتين'],
            'shelf_life' => ['label' => 'مدة الصلاحية بالأيام', 'type' => 'number'],
        ],
    ],
    'restaurant' => [
        'label' => 'مطعم ووجبات',
        'description' => 'مكونات، أحجام وجبات، إضافات ووقت تحضير.',
        'suggested_categories' => ['وجبات رئيسية', 'مقبلات', 'ساندويشات', 'مشروبات', 'حلويات', 'وجبات أطفال', 'عروض'],
        'icon' => 'ti-tools-kitchen-2',
        'fields' => [
            'meal_sizes' => ['label' => 'أحجام الوجبة', 'type' => 'list', 'placeholder' => 'مثال: صغير, وسط, كبير'],
            'meal_size_prices' => ['label' => 'أسعار الأحجام', 'type' => 'list', 'placeholder' => 'مثال: صغير:20, وسط:25, كبير:30'],
            'ingredients' => ['label' => 'المكونات', 'type' => 'textarea'],
            'removable_ingredients' => ['label' => 'مكونات يمكن للعميل حذفها', 'type' => 'list', 'placeholder' => 'مثال: بصل, مخلل, صوص'],
            'addons' => ['label' => 'الإضافات المتاحة', 'type' => 'list'],
            'addon_prices' => ['label' => 'أسعار الإضافات', 'type' => 'list', 'placeholder' => 'مثال: جبنة:3, صوص:2'],
            'preparation_time' => ['label' => 'وقت التحضير بالدقائق', 'type' => 'number'],
            'calories' => ['label' => 'السعرات الحرارية', 'type' => 'number'],
            'spice_level' => ['label' => 'درجة الحدة', 'type' => 'select', 'options' => ['غير حار', 'خفيف', 'متوسط', 'حار']],
            'dietary' => ['label' => 'التصنيف الغذائي', 'type' => 'select', 'options' => ['عادي', 'نباتي', 'فيغان', 'خالٍ من الجلوتين']],
        ],
    ],
    'electronics' => [
        'label' => 'جوالات وإلكترونيات',
        'description' => 'جوالات وتابلت وساعات وإكسسوارات مع مواصفات تقنية وخيارات مخزون مستقلة.',
        'suggested_categories' => ['جوالات', 'تابلت', 'ساعات ذكية', 'إكسسوارات'],
        'icon' => 'ti-device-mobile',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'model' => ['label' => 'الموديل', 'type' => 'text'],
            'condition' => ['label' => 'حالة البيع', 'type' => 'select', 'options' => ['جديد', 'مستعمل']],
            'condition_notes' => ['label' => 'وصف حالة الجهاز', 'type' => 'textarea', 'placeholder' => 'الخدوش، القطع المستبدلة، ونتيجة الفحص للمستعمل'],
            'battery_health' => ['label' => 'نسبة صحة البطارية للمستعمل', 'type' => 'number'],
            'sim_type' => ['label' => 'نوع الشريحة', 'type' => 'select', 'options' => ['شريحة واحدة', 'شريحتان', 'شريحة + eSIM', 'eSIM فقط']],
            'supports_esim' => ['label' => 'يدعم eSIM', 'type' => 'boolean'],
            'network' => ['label' => 'الشبكة', 'type' => 'select', 'options' => ['4G', '5G']],
            'screen_size' => ['label' => 'حجم الشاشة', 'type' => 'text', 'placeholder' => 'مثال: 6.7 بوصة'],
            'processor' => ['label' => 'المعالج', 'type' => 'text'],
            'battery' => ['label' => 'البطارية', 'type' => 'text', 'placeholder' => 'مثال: 5000mAh'],
            'cameras' => ['label' => 'الكاميرات', 'type' => 'textarea'],
            'warranty_months' => ['label' => 'مدة الضمان بالأشهر', 'type' => 'number'],
            'included_accessories' => ['label' => 'الملحقات المرفقة', 'type' => 'list', 'placeholder' => 'مثال: شاحن، كابل، كفر'],
        ],
    ],
    'real_estate' => [
        'label' => 'شركة عقارات',
        'description' => 'بيع وتأجير العقارات بواجهة مستقلة وروابط خاصة بالشركة.',
        'requires_distributor' => false,
        'suggested_categories' => [],
        'icon' => 'ti-building-community',
        'uses_products' => false,
        'fields' => [],
    ],
    'cosmetics' => [
        'label' => 'كوزماتيكس وعناية',
        'description' => 'درجات، نوع بشرة، حجم، مكونات وطريقة استخدام.',
        'suggested_categories' => ['مكياج', 'عناية بالبشرة', 'عناية بالشعر', 'عطور', 'أظافر', 'أدوات تجميل', 'عناية بالجسم'],
        'icon' => 'ti-spray',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'shades' => ['label' => 'الدرجات أو الألوان', 'type' => 'list'],
            'skin_types' => ['label' => 'نوع البشرة المناسب', 'type' => 'list', 'placeholder' => 'مثال: دهنية, جافة, حساسة'],
            'volume' => ['label' => 'الحجم أو السعة', 'type' => 'text', 'placeholder' => 'مثال: 50 مل'],
            'ingredients' => ['label' => 'المكونات الفعالة', 'type' => 'textarea'],
            'usage' => ['label' => 'طريقة الاستخدام', 'type' => 'textarea'],
            'expiry_after_opening' => ['label' => 'الصلاحية بعد الفتح بالأشهر', 'type' => 'number'],
            'cruelty_free' => ['label' => 'خالٍ من التجارب على الحيوانات', 'type' => 'boolean'],
        ],
    ],
];
