<?php

return [
    'general' => [
        'label' => 'متجر عام',
        'description' => 'منتجات عامة بدون خصائص متخصصة.',
        'suggested_categories' => ['الأكثر مبيعًا', 'وصل حديثًا', 'عروض', 'منتجات متنوعة'],
        'icon' => 'ti-building-store',
        'fields' => [
            'brand' => ['label' => 'العلامة التجارية', 'type' => 'text'],
            'model' => ['label' => 'الموديل أو الإصدار', 'type' => 'text'],
            'unit' => ['label' => 'وحدة البيع', 'type' => 'select', 'options' => ['قطعة', 'عبوة', 'كرتونة', 'كيلوغرام', 'لتر']],
        ],
    ],
    'clothing' => [
        'label' => 'ملابس وأزياء',
        'description' => 'مقاسات، ألوان، خامات، جنس وموسم.',
        'suggested_categories' => ['رجالي', 'نسائي', 'أطفال', 'قمصان', 'بناطيل', 'فساتين', 'جاكيتات', 'إكسسوارات'],
        'icon' => 'ti-shirt',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'gender' => ['label' => 'الفئة', 'type' => 'select', 'options' => ['رجالي', 'نسائي', 'أطفال', 'يونيسكس']],
            'sizes' => ['label' => 'المقاسات المتوفرة', 'type' => 'list', 'placeholder' => 'مثال: S, M, L, XL'],
            'colors' => ['label' => 'الألوان المتوفرة', 'type' => 'list', 'placeholder' => 'مثال: أسود, أبيض, أزرق'],
            'material' => ['label' => 'الخامة أو القماش', 'type' => 'text'],
            'season' => ['label' => 'الموسم', 'type' => 'select', 'options' => ['صيفي', 'شتوي', 'كل المواسم']],
            'care' => ['label' => 'تعليمات الغسيل والعناية', 'type' => 'textarea'],
        ],
    ],
    'shoes' => [
        'label' => 'أحذية',
        'description' => 'مقاسات أحذية، ألوان، خامة ونوع استخدام.',
        'suggested_categories' => ['رجالي', 'نسائي', 'أطفال', 'رياضي', 'رسمي', 'صنادل', 'أحذية عمل'],
        'icon' => 'ti-shoe',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'gender' => ['label' => 'الفئة', 'type' => 'select', 'options' => ['رجالي', 'نسائي', 'أطفال', 'يونيسكس']],
            'sizes' => ['label' => 'النمر أو المقاسات', 'type' => 'list', 'placeholder' => 'مثال: 36, 37, 38, 39'],
            'colors' => ['label' => 'الألوان المتوفرة', 'type' => 'list'],
            'material' => ['label' => 'الخامة', 'type' => 'text'],
            'shoe_use' => ['label' => 'الاستخدام', 'type' => 'select', 'options' => ['رياضي', 'رسمي', 'يومي', 'منزلي', 'عمل']],
        ],
    ],
    'sweets' => [
        'label' => 'حلويات ومخبوزات',
        'description' => 'نكهات، وزن، عدد القطع، مناسبة وحساسيات.',
        'suggested_categories' => ['كيك', 'حلويات شرقية', 'حلويات غربية', 'شوكولاتة', 'مخبوزات', 'ضيافة', 'مناسبات'],
        'icon' => 'ti-cake',
        'fields' => [
            'sweet_type' => ['label' => 'نوع الحلوى', 'type' => 'text'],
            'flavors' => ['label' => 'النكهات المتوفرة', 'type' => 'list'],
            'weight' => ['label' => 'الوزن أو الحجم', 'type' => 'text', 'placeholder' => 'مثال: 500 غرام'],
            'pieces' => ['label' => 'عدد القطع', 'type' => 'number'],
            'occasion' => ['label' => 'المناسبة', 'type' => 'select', 'options' => ['يومي', 'أعياد ميلاد', 'أعراس', 'ضيافة', 'مناسبات']],
            'allergens' => ['label' => 'مسببات الحساسية', 'type' => 'list', 'placeholder' => 'مثال: مكسرات, حليب, جلوتين'],
            'shelf_life' => ['label' => 'مدة الصلاحية بالأيام', 'type' => 'number'],
        ],
    ],
    'restaurant' => [
        'label' => 'مطعم ووجبات',
        'description' => 'مكونات، أحجام وجبات، إضافات ووقت تحضير.',
        'suggested_categories' => ['وجبات رئيسية', 'مقبلات', 'ساندويشات', 'مشروبات', 'حلويات', 'وجبات أطفال', 'عروض'],
        'icon' => 'ti-tools-kitchen-2',
        'fields' => [
            'meal_sizes' => ['label' => 'أحجام الوجبة', 'type' => 'list', 'placeholder' => 'مثال: صغير, وسط, كبير'],
            'ingredients' => ['label' => 'المكونات', 'type' => 'textarea'],
            'addons' => ['label' => 'الإضافات المتاحة', 'type' => 'list'],
            'preparation_time' => ['label' => 'وقت التحضير بالدقائق', 'type' => 'number'],
            'calories' => ['label' => 'السعرات الحرارية', 'type' => 'number'],
            'spice_level' => ['label' => 'درجة الحدة', 'type' => 'select', 'options' => ['غير حار', 'خفيف', 'متوسط', 'حار']],
            'dietary' => ['label' => 'التصنيف الغذائي', 'type' => 'select', 'options' => ['عادي', 'نباتي', 'فيغان', 'خالٍ من الجلوتين']],
            'allergens' => ['label' => 'مسببات الحساسية', 'type' => 'list'],
        ],
    ],
    'cosmetics' => [
        'label' => 'كوزماتيكس وعناية',
        'description' => 'درجات، نوع بشرة، حجم، مكونات وطريقة استخدام.',
        'suggested_categories' => ['مكياج', 'عناية بالبشرة', 'عناية بالشعر', 'عطور', 'أظافر', 'أدوات تجميل', 'عناية بالجسم'],
        'icon' => 'ti-spray',
        'fields' => [
            'brand' => ['label' => 'الماركة', 'type' => 'text'],
            'shades' => ['label' => 'الدرجات أو الألوان', 'type' => 'list'],
            'skin_types' => ['label' => 'نوع البشرة المناسب', 'type' => 'list', 'placeholder' => 'مثال: دهنية, جافة, حساسة'],
            'volume' => ['label' => 'الحجم أو السعة', 'type' => 'text', 'placeholder' => 'مثال: 50 مل'],
            'ingredients' => ['label' => 'المكونات الفعالة', 'type' => 'textarea'],
            'usage' => ['label' => 'طريقة الاستخدام', 'type' => 'textarea'],
            'expiry_after_opening' => ['label' => 'الصلاحية بعد الفتح بالأشهر', 'type' => 'number'],
            'cruelty_free' => ['label' => 'خالٍ من التجارب على الحيوانات', 'type' => 'boolean'],
        ],
    ],
];
