<?php

$general = [
    'item_singular' => 'منتج',
    'item_plural' => 'المنتجات',
    'add_item' => 'إضافة منتج',
    'category_singular' => 'الفئة',
    'category_plural' => 'الفئات',
    'add_category' => 'إضافة فئة',
    'place_singular' => 'المتجر',
    'dashboard_label' => 'لوحة المتجر',
];

return [
    'general' => $general,
    'clothing' => array_replace($general, [
        'item_singular' => 'قطعة أزياء',
        'item_plural' => 'قطع الأزياء',
        'add_item' => 'إضافة قطعة أزياء',
        'category_singular' => 'قسم الملابس',
        'category_plural' => 'أقسام الملابس',
        'add_category' => 'إضافة قسم ملابس',
        'place_singular' => 'متجر الأزياء',
        'dashboard_label' => 'لوحة متجر الأزياء',
    ]),
    'shoes' => array_replace($general, [
        'item_singular' => 'حذاء',
        'item_plural' => 'الأحذية',
        'add_item' => 'إضافة حذاء',
        'category_singular' => 'قسم الأحذية',
        'category_plural' => 'أقسام الأحذية',
        'add_category' => 'إضافة قسم أحذية',
        'place_singular' => 'متجر الأحذية',
        'dashboard_label' => 'لوحة متجر الأحذية',
    ]),
    'sweets' => array_replace($general, [
        'item_singular' => 'صنف',
        'item_plural' => 'أصناف الحلويات',
        'add_item' => 'إضافة صنف',
        'category_singular' => 'قسم الحلويات',
        'category_plural' => 'أقسام الحلويات',
        'add_category' => 'إضافة قسم حلويات',
        'place_singular' => 'محل الحلويات',
        'dashboard_label' => 'لوحة محل الحلويات',
    ]),
    'restaurant' => array_replace($general, [
        'item_singular' => 'وجبة',
        'item_plural' => 'الوجبات',
        'add_item' => 'إضافة وجبة جديدة',
        'category_singular' => 'قسم المنيو',
        'category_plural' => 'أقسام المنيو',
        'add_category' => 'إضافة قسم منيو جديد',
        'place_singular' => 'المطعم',
        'dashboard_label' => 'لوحة المطعم',
    ]),
    'electronics' => array_replace($general, [
        'item_singular' => 'جهاز',
        'item_plural' => 'الأجهزة والإلكترونيات',
        'add_item' => 'إضافة جهاز',
        'category_singular' => 'قسم الأجهزة',
        'category_plural' => 'أقسام الأجهزة',
        'add_category' => 'إضافة قسم أجهزة',
        'place_singular' => 'متجر الإلكترونيات',
        'dashboard_label' => 'لوحة متجر الإلكترونيات',
    ]),
    'furniture_appliances' => array_replace($general, [
        'item_singular' => 'قطعة أو جهاز',
        'item_plural' => 'الأثاث والأجهزة',
        'add_item' => 'إضافة قطعة أو جهاز',
        'category_singular' => 'قسم العرض',
        'category_plural' => 'أقسام المعرض',
        'add_category' => 'إضافة قسم للمعرض',
        'place_singular' => 'معرض الأثاث والأجهزة',
        'dashboard_label' => 'لوحة معرض الأثاث والأجهزة',
    ]),
    'advertising_services' => array_replace($general, [
        'item_singular' => 'خدمة',
        'item_plural' => 'الخدمات الدعائية',
        'add_item' => 'إضافة خدمة',
        'category_singular' => 'قسم الخدمات',
        'category_plural' => 'أقسام الخدمات',
        'add_category' => 'إضافة قسم خدمات',
        'place_singular' => 'شركة الدعاية',
        'dashboard_label' => 'لوحة شركة الدعاية',
    ]),
    'real_estate' => array_replace($general, [
        'item_singular' => 'خدمة',
        'item_plural' => 'خدمات البناء',
        'add_item' => 'إضافة خدمة',
        'category_singular' => 'قسم الخدمات',
        'category_plural' => 'أقسام الخدمات',
        'add_category' => 'إضافة قسم خدمات',
        'place_singular' => 'شركة البناء',
        'dashboard_label' => 'لوحة شركة البناء',
    ]),
    'cosmetics' => array_replace($general, [
        'item_singular' => 'مستحضر',
        'item_plural' => 'مستحضرات التجميل',
        'add_item' => 'إضافة مستحضر',
        'category_singular' => 'قسم المستحضرات',
        'category_plural' => 'أقسام المستحضرات',
        'add_category' => 'إضافة قسم مستحضرات',
        'place_singular' => 'متجر التجميل',
        'dashboard_label' => 'لوحة متجر التجميل',
    ]),
];
