<?php

return [
    'groups' => [
        'dashboard' => [
            'label' => 'لوحات التحكم والملخصات',
            'description' => 'الدخول للصفحات الرئيسية والإحصائيات، دون منح صلاحية تعديل الأقسام الأخرى.',
            'permissions' => [
                'dashboard.view' => ['label' => 'فتح لوحة البداية', 'description' => 'الدخول إلى صفحة البداية المناسبة للحساب.', 'routes' => ['dashboard']],
                'dashboard.main' => ['label' => 'عرض لوحة الإدارة الرئيسية', 'description' => 'مشاهدة ملخصات وإحصائيات النظام العامة.', 'routes' => ['dashboard.main']],
            ],
        ],
        'shops' => [
            'label' => 'المتاجر والمحلات',
            'description' => 'إدارة المتاجر الواقعة ضمن نطاق المستخدم أو الموزع.',
            'permissions' => [
                'shops.view' => ['label' => 'عرض المتاجر وتفاصيلها', 'description' => 'مشاهدة قائمة المتاجر وملف كل متجر.', 'routes' => ['shops', 'shops.show', 'shops.ozman']],
                'shops.create' => ['label' => 'إضافة متجر جديد', 'description' => 'إنشاء متجر وربطه بصاحب متجر أو بالجهة التي أضافته.', 'routes' => ['shops.create', 'shops.store']],
                'shops.marketer_create' => ['label' => 'إضافة محل تابع للمسوّق', 'description' => 'للمسوّق: إنشاء محل يُنسب له وتصل طلباته إلى موزعه.', 'routes' => ['shops', 'shops.create', 'shops.store']],
                'shops.edit' => ['label' => 'تعديل بيانات متجر', 'description' => 'تعديل متجر يقع ضمن نطاق هذا الحساب.', 'routes' => ['shops.edit', 'shops.update']],
                'shops.delete' => ['label' => 'حذف متجر', 'description' => 'حذف متجر وبياناته المرتبطة؛ صلاحية حساسة.', 'routes' => ['shops.destroy']],
            ],
        ],
        'products' => [
            'label' => 'منتجات المتاجر',
            'description' => 'المنتجات التابعة للمتاجر التي يستطيع الحساب الوصول إليها.',
            'permissions' => [
                'products.view' => ['label' => 'عرض منتجات المتاجر', 'description' => 'مشاهدة قائمة المنتجات وتفاصيلها.', 'routes' => ['products', 'products.show']],
                'products.preview' => ['label' => 'معاينة واجهة المتجر', 'description' => 'معاينة طريقة ظهور المنتجات للعملاء.', 'routes' => ['products.preview']],
                'products.create' => ['label' => 'إضافة منتج لمتجر', 'description' => 'إنشاء منتج في متجر مسموح بإدارته.', 'routes' => ['products.create', 'products.store']],
                'products.edit' => ['label' => 'تعديل منتج وأسعاره ومخزونه', 'description' => 'تعديل بيانات المنتج وظهوره وأسعاره.', 'routes' => ['products.edit', 'products.update']],
                'products.delete' => ['label' => 'حذف منتج من متجر', 'description' => 'حذف المنتج؛ صلاحية حساسة.', 'routes' => ['products.destroy']],
            ],
        ],
        'categories' => [
            'label' => 'فئات منتجات المتاجر',
            'description' => 'الفئات التي تنظّم منتجات كل متجر وليست فئات عامة مستقلة.',
            'permissions' => [
                'categories.view' => ['label' => 'عرض فئات المتاجر', 'description' => 'مشاهدة الفئات وتفاصيلها.', 'routes' => ['categories', 'categories.show']],
                'categories.create' => ['label' => 'إضافة فئة لمتجر', 'description' => 'إنشاء فئة وربطها بمتجر محدد.', 'routes' => ['categories.create', 'categories.store']],
                'categories.edit' => ['label' => 'تعديل فئة متجر', 'description' => 'تعديل اسم الفئة وصورتها وترتيبها.', 'routes' => ['categories.edit', 'categories.update']],
                'categories.delete' => ['label' => 'حذف فئة متجر', 'description' => 'حذف الفئة؛ صلاحية حساسة.', 'routes' => ['categories.destroy']],
            ],
        ],
        'ads' => [
            'label' => 'إعلانات المتاجر',
            'description' => 'الإعلانات التي تظهر في واجهات المتاجر المسموح بإدارتها.',
            'permissions' => [
                'ads.view' => ['label' => 'عرض إعلانات المتاجر', 'description' => 'مشاهدة الإعلانات وتفاصيلها.', 'routes' => ['ads', 'ads.show']],
                'ads.create' => ['label' => 'إضافة إعلان لمتجر', 'description' => 'إنشاء إعلان وربطه بمتجر.', 'routes' => ['ads.create', 'ads.store']],
                'ads.edit' => ['label' => 'تعديل إعلان متجر', 'description' => 'تعديل محتوى الإعلان وحالة ظهوره.', 'routes' => ['ads.edit', 'ads.update']],
                'ads.delete' => ['label' => 'حذف إعلان متجر', 'description' => 'حذف الإعلان؛ صلاحية حساسة.', 'routes' => ['ads.destroy']],
            ],
        ],
        'screens' => [
            'label' => 'شاشات العرض التابعة للمتاجر',
            'description' => 'الشاشات الإعلانية ومواضع ظهور المحتوى عليها.',
            'permissions' => [
                'screens.view' => ['label' => 'عرض الشاشات التابعة للحساب', 'description' => 'مشاهدة الشاشات ضمن نطاق الحساب فقط.', 'routes' => ['screens', 'screens.show']],
                'screens.view_all' => ['label' => 'عرض جميع شاشات النظام', 'description' => 'تجاوز نطاق الحساب؛ مناسبة للإدارة العليا.', 'routes' => []],
                'screens.create' => ['label' => 'إضافة شاشة لمتجر', 'description' => 'إنشاء شاشة عرض وربطها بمتجر.', 'routes' => ['screens.create', 'screens.store']],
                'screens.edit' => ['label' => 'تعديل شاشة متجر', 'description' => 'تعديل بيانات الشاشة ومحتواها.', 'routes' => ['screens.edit', 'screens.update']],
                'screens.delete' => ['label' => 'حذف شاشة متجر', 'description' => 'حذف الشاشة؛ صلاحية حساسة.', 'routes' => ['screens.destroy']],
                'screens.place_top' => ['label' => 'السماح بالعرض في الموضع العلوي', 'description' => 'اختيار الشاشة العلوية لعرض المحتوى.', 'routes' => []],
                'screens.place_bottom' => ['label' => 'السماح بالعرض في الموضع السفلي', 'description' => 'اختيار الشاشة السفلية لعرض المحتوى.', 'routes' => []],
            ],
        ],
        'people' => [
            'label' => 'الوكلاء والموزعون ومسوّقوهم',
            'description' => 'حسابات شبكة التوزيع، وليست حسابات أصحاب المتاجر أو موظفي الإدارة.',
            'permissions' => [
                'agents.view' => ['label' => 'عرض الوكلاء', 'description' => 'مشاهدة قائمة الوكلاء وتفاصيلهم.', 'routes' => ['agents', 'agents.show']],
                'agents.create' => ['label' => 'إضافة وكيل', 'description' => 'إنشاء حساب وكيل جديد.', 'routes' => ['agents.create', 'agents.store']],
                'agents.edit' => ['label' => 'تعديل بيانات وكيل', 'description' => 'تعديل بيانات الوكيل وحالته.', 'routes' => ['agents.edit', 'agents.update']],
                'agents.delete' => ['label' => 'حذف وكيل', 'description' => 'حذف الوكيل؛ صلاحية حساسة.', 'routes' => ['agents.destroy']],
                'agents.permissions' => ['label' => 'تعديل صلاحيات الوكلاء', 'description' => 'تحديد أقسام وعمليات الوكيل.', 'routes' => ['agents.permissions.edit', 'agents.permissions.update']],
                'distributors.view' => ['label' => 'عرض الموزعين ومتاجرهم', 'description' => 'مشاهدة الموزعين والمتاجر المرتبطة بهم.', 'routes' => ['distributors', 'distributors.show']],
                'distributors.create' => ['label' => 'إضافة موزع', 'description' => 'إنشاء حساب موزع جديد.', 'routes' => ['distributors.create', 'distributors.store']],
                'distributors.edit' => ['label' => 'تعديل بيانات موزع', 'description' => 'تعديل بيانات الموزع وحالته.', 'routes' => ['distributors.edit', 'distributors.update']],
                'distributors.delete' => ['label' => 'حذف موزع', 'description' => 'حذف الموزع؛ صلاحية حساسة.', 'routes' => ['distributors.destroy']],
                'distributors.permissions' => ['label' => 'تعديل صلاحيات الموزعين', 'description' => 'تحديد أقسام وعمليات الموزع.', 'routes' => ['distributors.permissions.edit', 'distributors.permissions.update']],
                'distributors.marketers' => ['label' => 'إدارة مسوّقي الموزعين وعمولاتهم', 'description' => 'إضافة المسوّقين وتعديلهم وحذفهم وتحديد النسبة.', 'routes' => ['distributors.marketers.index', 'distributors.marketers.store', 'distributors.marketers.update', 'distributors.marketers.commission.update', 'distributors.marketers.destroy']],
                'distributors.marketers.permissions' => ['label' => 'تعديل صلاحيات مسوّقي الموزعين', 'description' => 'تحديد ما يستطيع كل مسوّق الوصول إليه.', 'routes' => ['distributors.marketers.permissions.edit', 'distributors.marketers.permissions.update']],
            ],
        ],
        'orders' => [
            'label' => 'طلبات العملاء والتسجيلات والبطاقات',
            'description' => 'طلبات واجهة المتجر، طلبات التسجيل، وجوائز بطاقات السحب.',
            'permissions' => [
                'restaurant.view' => ['label' => 'عرض لوحة المطعم وطلباته مباشرة', 'description' => 'مشاهدة طلبات المطعم والطاولات واستقبال الطلبات الجديدة تلقائياً ضمن المتجر المسموح فقط.', 'routes' => ['restaurant.dashboard', 'restaurant.orders.feed']],
                'restaurant.tables.manage' => ['label' => 'إدارة طاولات المطعم وQR', 'description' => 'إضافة وحذف طاولات المطعم وتحميل رموز QR.', 'routes' => ['restaurant.tables.store', 'restaurant.tables.destroy', 'restaurant.tables.qr']],
                'restaurant.orders.manage' => ['label' => 'تحديث حالات طلبات المطعم', 'description' => 'نقل الطلب من جديد إلى التحضير ثم جاهز ومكتمل أو إلغائه.', 'routes' => ['restaurant.orders.status']],
                'visitor_registrations.view' => ['label' => 'إدارة تسجيلات العملاء وأصحاب المتاجر', 'description' => 'مشاهدة طلبات التسجيل وقبولها أو رفضها.', 'routes' => ['visitor-registrations.index', 'visitor-registrations.status.update']],
                'front_orders.view' => ['label' => 'عرض وإدارة طلبات المتاجر', 'description' => 'مشاهدة الطلبات ضمن النطاق وتغيير حالتها.', 'routes' => ['front-orders.index', 'front-orders.status']],
                'marketer_orders.view' => ['label' => 'عرض طلبات رابط المسوّق فقط', 'description' => 'للمسوّق: طلباته المنسوبة له دون باقي طلبات الموزع.', 'routes' => ['front-orders.index']],
                'front_orders.manage' => ['label' => 'إدارة جوائز الطلبات', 'description' => 'تسجيل وتشغيل الجائزة المرتبطة بالطلب.', 'routes' => ['front-orders.reward', 'front-orders.spinReward']],
                'raffle_cards.inspect' => ['label' => 'فحص رقم بطاقة رابحة فقط', 'description' => 'البحث برقم بطاقة واحد ومعرفة إن كانت رابحة وحالتها، بدون عرض القائمة أو الإضافة والتعديل والحذف.', 'routes' => ['raffle-cards.inspector']],
                'raffle_cards.view' => ['label' => 'عرض وتصدير بطاقات السحب', 'description' => 'مشاهدة بطاقات الربح والسحب المباشر وتصدير الأرقام الرابحة إلى PDF.', 'routes' => ['raffle-cards.index', 'raffle-cards.export-pdf']],
                'raffle_cards.create' => ['label' => 'إنشاء وطباعة بطاقات ربح', 'description' => 'إضافة بطاقة منفردة أو مجموعة عشوائية وتجهيز البطاقات للطباعة.', 'routes' => ['raffle-cards.store', 'raffle-cards.random-bulk', 'raffle-cards.printable']],
                'raffle_cards.edit' => ['label' => 'تعديل بطاقات وإعدادات السحب', 'description' => 'تعديل البطاقة وإعدادات السحب.', 'routes' => ['raffle-cards.update', 'raffle-cards.settings']],
                'raffle_cards.delete' => ['label' => 'حذف بطاقات أو نتائج سحب', 'description' => 'حذف بطاقة واحدة أو عدة بطاقات ومدخلات السحب؛ صلاحية حساسة.', 'routes' => ['raffle-cards.destroy', 'raffle-cards.bulk-destroy', 'raffle-cards.live-draw.destroy', 'raffle-cards.live-draw.bulk-destroy']],
            ],
        ],
        'real_estate' => [
            'label' => 'إدارة شركات العقارات',
            'description' => 'إدارة العقارات والصور وطلبات العملاء ضمن الشركات المسموح للحساب بالوصول إليها.',
            'permissions' => [
                'real_estate.view' => ['label' => 'عرض لوحة العقارات', 'description' => 'مشاهدة العقارات والإحصائيات والعملاء.', 'routes' => ['real-estate.dashboard', 'real-estate.company.qr']],
                'real_estate.create' => ['label' => 'إضافة عقارات', 'description' => 'إنشاء عقار جديد ورفع صوره.', 'routes' => ['real-estate.dashboard.properties.create', 'real-estate.dashboard.properties.store']],
                'real_estate.edit' => ['label' => 'تعديل العقارات والصور', 'description' => 'تعديل البيانات والحالة والصور واختيار الغلاف.', 'routes' => ['real-estate.dashboard.properties.edit', 'real-estate.dashboard.properties.update', 'real-estate.dashboard.images.destroy', 'real-estate.dashboard.images.cover', 'real-estate.dashboard.images.move']],
                'real_estate.delete' => ['label' => 'حذف العقارات', 'description' => 'حذف العقار وجميع صوره؛ صلاحية حساسة.', 'routes' => ['real-estate.dashboard.properties.destroy']],
                'real_estate.leads' => ['label' => 'إدارة العملاء والمعاينات', 'description' => 'تحديث حالة العميل وموعد المعاينة.', 'routes' => ['real-estate.dashboard.leads.update']],
            ],
        ],
        'reward_wheels' => [
            'label' => 'عجلات الربح والشراء والتسويق',
            'description' => 'كل نوع عجلة مستقل؛ امنح فقط النوع الذي يحتاجه المستخدم.',
            'permissions' => [
                'reward_wheels.customer_signup.view' => ['label' => 'عرض عجلة تسجيل العملاء', 'description' => 'مشاهدة إعدادات عجلة ما بعد التسجيل.', 'routes' => ['reward-wheels.customer-signup.edit']],
                'reward_wheels.customer_signup.edit' => ['label' => 'تعديل عجلة تسجيل العملاء', 'description' => 'تعديل شرائح وجوائز عجلة التسجيل.', 'routes' => ['reward-wheels.customer-signup.update']],
                'reward_wheels.purchase.view' => ['label' => 'عرض عجلات شراء المتاجر', 'description' => 'مشاهدة عجلات شراء المتاجر ضمن نطاق الحساب.', 'routes' => ['reward-wheels.purchase.index', 'reward-wheels.purchase.edit']],
                'reward_wheels.purchase.manage' => ['label' => 'إدارة عجلات شراء المتاجر', 'description' => 'إضافة وتعديل وحذف عجلات شراء المتاجر.', 'routes' => ['reward-wheels.purchase.store', 'reward-wheels.purchase.update', 'reward-wheels.purchase.destroy']],
                'reward_wheels.marketer.view' => ['label' => 'عرض عجلة أسئلة المسوّق', 'description' => 'مشاهدة إعدادات عجلة الأسئلة التسويقية.', 'routes' => ['reward-wheels.marketer.edit']],
                'reward_wheels.marketer.edit' => ['label' => 'تعديل عجلة أسئلة المسوّق', 'description' => 'تعديل الأسئلة والجوائز والإعدادات.', 'routes' => ['reward-wheels.marketer.update']],
                'reward_wheels.marketer.play' => ['label' => 'تشغيل عجلة أسئلة المسوّق', 'description' => 'الإجابة والفتح والسحب وإعادة البدء.', 'routes' => ['reward-wheels.marketer.play', 'reward-wheels.marketer.unlock', 'reward-wheels.marketer.spin', 'reward-wheels.marketer.reset']],
                'reward_wheels.marketer_direct.view' => ['label' => 'عرض عجلة المسوّق المباشرة', 'description' => 'مشاهدة إعدادات العجلة المباشرة.', 'routes' => ['reward-wheels.marketer.direct.edit']],
                'reward_wheels.marketer_direct.edit' => ['label' => 'تعديل عجلة المسوّق المباشرة', 'description' => 'تعديل شرائح وإعدادات العجلة المباشرة.', 'routes' => ['reward-wheels.marketer.direct.update']],
                'reward_wheels.marketer_direct.play' => ['label' => 'تشغيل عجلة المسوّق المباشرة', 'description' => 'فتح صفحة التشغيل وإجراء السحب.', 'routes' => ['reward-wheels.marketer.direct.play', 'reward-wheels.marketer.direct.spin']],
            ],
        ],
        'employees' => [
            'label' => 'موظفو لوحة الإدارة وصلاحياتهم',
            'description' => 'موظفو الإدارة الداخلية، وليس الموزعين أو أصحاب المتاجر.',
            'permissions' => [
                'employees.view' => ['label' => 'عرض موظفي الإدارة', 'description' => 'مشاهدة قائمة الموظفين.', 'routes' => ['employees', 'employees.show']],
                'employees.create' => ['label' => 'إضافة موظف إدارة', 'description' => 'إنشاء حساب موظف جديد.', 'routes' => ['employees.create', 'employees.store']],
                'employees.edit' => ['label' => 'تعديل موظف إدارة', 'description' => 'تعديل بيانات الموظف وحالته.', 'routes' => ['employees.edit', 'employees.update']],
                'employees.delete' => ['label' => 'حذف موظف إدارة', 'description' => 'حذف الموظف؛ صلاحية حساسة.', 'routes' => ['employees.destroy']],
                'employees.permissions' => ['label' => 'تعديل صلاحيات موظفي الإدارة', 'description' => 'منح أو سحب صلاحيات الموظفين.', 'routes' => ['employees.permissions.edit', 'employees.permissions.update']],
            ],
        ],
        'users' => [
            'label' => 'جميع حسابات المستخدمين',
            'description' => 'قائمة الحسابات بمختلف أدوارها؛ مناسبة للإدارة العليا.',
            'permissions' => [
                'users.view' => ['label' => 'عرض جميع المستخدمين', 'description' => 'مشاهدة الحسابات وأدوارها وحالتها.', 'routes' => ['users']],
            ],
        ],
        'settings' => [
            'label' => 'إعدادات الحساب والنظام',
            'description' => 'افصل بين الإعدادات الشخصية والإعدادات العامة التي تؤثر على الجميع.',
            'permissions' => [
                'settings.view' => ['label' => 'فتح صفحة الإعدادات', 'description' => 'مشاهدة صفحة الإعدادات.', 'routes' => ['settings']],
                'settings.profile' => ['label' => 'تعديل الملف الشخصي للحساب', 'description' => 'تعديل بيانات الحساب الحالي.', 'routes' => ['settings.profile.update']],
                'settings.password' => ['label' => 'تغيير كلمة مرور الحساب', 'description' => 'تغيير كلمة مرور الحساب الحالي.', 'routes' => ['settings.password.update']],
                'settings.system' => ['label' => 'تعديل إعدادات النظام العامة', 'description' => 'تغييرات تؤثر على النظام كله؛ للإدارة العليا.', 'routes' => ['settings.system.update']],
                'settings.notifications' => ['label' => 'تعديل إعدادات الإشعارات', 'description' => 'تحديد أنواع الإشعارات وطريقة عرضها.', 'routes' => ['settings.notifications.update']],
                'notifications.manage' => ['label' => 'إدارة إشعارات لوحة الإدارة', 'description' => 'تعيين إشعارات الإدارة كمقروءة.', 'routes' => ['admin.notifications.readAll']],
            ],
        ],
    ],
];
