<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>إدارة مطعم {{ $shop->name }}</title><style>
body{margin:0;background:#05070b;color:#fff;font-family:Arial,sans-serif}.wrap{max-width:1300px;margin:auto;padding:24px}a{color:#00e5ff}.head,.panel{background:#10151b;border:1px solid #24313b;border-radius:20px;padding:20px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.card{background:#080b0f;border:1px solid #26333c;border-radius:16px;padding:15px}input,select,button{padding:11px;border-radius:10px;border:1px solid #34434c;background:#111820;color:#fff}button{background:#00d8ef;color:#001014;font-weight:bold;cursor:pointer}.danger{background:#47151b;color:#ffb5bd}.tag{display:inline-block;padding:5px 9px;border-radius:20px;background:#16343b;color:#4cecff}table{width:100%;border-collapse:collapse}td,th{padding:11px;border-bottom:1px solid #253039;text-align:right}@media(max-width:700px){.wrap{padding:10px}.table-wrap{overflow:auto}}
.wrap{margin-right:245px}@media(max-width:900px){.wrap{margin-right:0}}
</style></head><body>@include('admin.includes.sidebar')<main class="wrap">
<section class="head"><a href="{{ route('shops.show',$shop) }}">← لوحة المتجر</a><h1>إدارة مطعم {{ $shop->name }}</h1><p>الطاولات، شاشة المطبخ والكاشير، والطلبات الأونلاين.</p><a href="{{ route('restaurant.menu',$shop) }}" target="_blank">فتح منيو المطعم</a></section>
@if(session('status'))<div class="panel">{{ session('status') }}</div>@endif
@if($errors->any())<div class="panel" style="border-color:#ff5d6c;color:#ffb5bd"><b>تعذر تنفيذ العملية:</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="grid" style="margin-bottom:18px"><div class="card"><b>طلبات اليوم</b><h2>{{ $stats['today'] }}</h2></div><div class="card"><b>جديدة</b><h2>{{ $stats['new'] }}</h2></div><div class="card"><b>قيد التحضير</b><h2>{{ $stats['preparing'] }}</h2></div><div class="card"><b>جاهزة</b><h2>{{ $stats['ready'] }}</h2></div></section>
<section class="panel"><h2>الطاولات وQR</h2><form method="post" action="{{ route('restaurant.tables.store',$shop) }}">@csrf <input name="name" placeholder="مثال: طاولة 1" required> <input name="capacity" type="number" min="1" placeholder="عدد المقاعد"> <button>إضافة طاولة</button></form>
<div class="grid" style="margin-top:16px">@forelse($tables as $table)<article class="card"><h3>{{ $table->name }}</h3><p>{{ $table->capacity ? $table->capacity.' مقاعد' : '' }}</p><img src="{{ route('restaurant.tables.qr',['table'=>$table->code]) }}" width="150" style="background:#fff;padding:8px"><p><a download href="{{ route('restaurant.tables.qr',['table'=>$table->code]) }}">تحميل QR</a></p><form method="post" action="{{ route('restaurant.tables.destroy',$table) }}">@csrf @method('delete')<button class="danger" onclick="return confirm('حذف الطاولة؟')">حذف</button></form></article>@empty<p>لا توجد طاولات بعد.</p>@endforelse</div></section>
<section class="panel"><h2>شاشة المطبخ والكاشير</h2><form method="get" style="margin-bottom:14px"><select name="type"><option value="">كل أنواع الطلب</option>@foreach(['dine_in'=>'داخل المطعم','delivery'=>'توصيل','pickup'=>'استلام'] as $k=>$v)<option value="{{ $k }}" @selected($selectedType===$k)>{{ $v }}</option>@endforeach</select> <select name="status"><option value="">كل الحالات</option>@foreach(['new'=>'جديد','preparing'=>'قيد التحضير','ready'=>'جاهز','completed'=>'مكتمل','cancelled'=>'ملغي'] as $k=>$v)<option value="{{ $k }}" @selected($selectedStatus===$k)>{{ $v }}</option>@endforeach</select> <button>فلترة</button></form><div class="table-wrap"><table><thead><tr><th>الطلب</th><th>المصدر</th><th>الزبون/الطاولة</th><th>التفاصيل</th><th>المجموع</th><th>الحالة</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td>{{ $order->order_number }}<br><small>{{ $order->created_at }}</small></td><td><span class="tag">{{ ['dine_in'=>'داخل المطعم','delivery'=>'توصيل','pickup'=>'استلام'][$order->order_type] ?? $order->order_type }}</span></td><td>{{ $order->restaurantTable?->name ?: $order->customer_name }}<br>{{ $order->customer_phone }}</td><td>@foreach($order->items ?? [] as $item)<div><b>{{ $item['qty'] }}× {{ $item['name'] }}</b> {{ $item['size'] ?? '' }}<br><small>إضافات: {{ implode('، ',$item['addons'] ?? []) ?: '-' }} | بدون: {{ implode('، ',$item['excluded'] ?? []) ?: '-' }} {{ $item['notes'] ?? '' }}</small></div>@endforeach</td><td>{{ $order->total }} ₪</td><td><form method="post" action="{{ route('restaurant.orders.status',$order) }}">@csrf @method('patch')<select name="status">@foreach(['new'=>'جديد','preparing'=>'قيد التحضير','ready'=>'جاهز','completed'=>'مكتمل','cancelled'=>'ملغي'] as $k=>$v)<option value="{{ $k }}" @selected($order->status===$k)>{{ $v }}</option>@endforeach</select><button>حفظ</button></form></td></tr>@empty<tr><td colspan="6">لا توجد طلبات.</td></tr>@endforelse
</tbody></table></div><div style="margin-top:15px">{{ $orders->links() }}</div></section></main></body></html>
