<!doctype html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ $shop->name }} | متجر التقنية</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
    <style>
        :root{--cyan:#21dcff;--violet:#7956ff;--bg:#05070c;--panel:#0a1018;--border:rgba(125,174,205,.2);--muted:#91a8b9}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 78% 4%,rgba(33,220,255,.09),transparent 28%),radial-gradient(circle at 8% 42%,rgba(121,86,255,.1),transparent 27%),var(--bg);color:#fff;font-family:Cairo,Segoe UI,sans-serif;overflow-x:hidden}a{color:inherit;text-decoration:none}button,input,select{font:inherit}.wrap{width:min(1380px,calc(100% - 32px));margin:auto}
        .hero{position:relative;isolation:isolate;overflow:hidden;min-height:400px;border-radius:0 0 38px 38px;background:linear-gradient(100deg,rgba(3,6,12,.97),rgba(5,14,24,.72)),var(--hero-image) center/cover,#07111e;border-bottom:1px solid rgba(33,220,255,.18)}.hero:after{content:"";position:absolute;z-index:-1;inset:0;background:linear-gradient(90deg,transparent 49.8%,rgba(33,220,255,.06) 50%,transparent 50.2%),linear-gradient(transparent 49.8%,rgba(33,220,255,.04) 50%,transparent 50.2%);background-size:90px 90px;transform:perspective(600px) rotateX(64deg) scale(1.8) translateY(33%);transform-origin:bottom}.hero-content{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(320px,.65fr);align-items:center;gap:42px;min-height:350px;padding:24px 34px}.hero-kicker{display:inline-flex;padding:8px 13px;border:1px solid rgba(33,220,255,.32);border-radius:999px;background:rgba(33,220,255,.07);color:var(--cyan);font-size:12px;font-weight:900}.hero h1{font-size:clamp(46px,6.5vw,78px);line-height:1;margin:18px 0 14px;background:linear-gradient(135deg,#fff 18%,#75eaff 52%,#947dff);-webkit-background-clip:text;color:transparent}.hero p{max-width:690px;color:#aec4d3;font-size:18px;line-height:1.9}.hero-webgl{justify-self:center;width:min(360px,34vw);height:340px;position:relative}.hero-webgl canvas{display:block;width:100%!important;height:100%!important}.webgl-fallback{position:absolute;inset:20%;display:grid;place-items:center;border:1px solid rgba(33,220,255,.2);border-radius:50%;color:var(--cyan)}
        .filters{display:grid;grid-template-columns:minmax(240px,2fr) repeat(5,minmax(105px,1fr));gap:8px;margin:-24px 0 24px;padding:14px;position:relative;z-index:8;border:1px solid rgba(33,220,255,.18);border-radius:18px;background:rgba(8,13,22,.88);backdrop-filter:blur(24px);box-shadow:0 18px 50px rgba(0,0,0,.38)}.filters input,.filters select,.filters button{min-width:0;height:42px;border:1px solid #22354a;border-radius:11px;background:#111a25;color:#fff;padding:0 12px}.filters button{border:0;background:linear-gradient(135deg,var(--cyan),#4ca9ff 52%,var(--violet));color:#00131c;font-weight:900}
        .catalog{min-height:660px;margin-bottom:100px;padding:24px;border:1px solid var(--border);border-radius:30px;background:linear-gradient(145deg,rgba(12,18,28,.95),rgba(5,9,14,.96));box-shadow:0 24px 70px rgba(0,0,0,.3)}.catalog-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:18px}.catalog-head h2{margin:0;font-size:28px}.catalog-head p{margin:3px 0;color:var(--muted);font-size:13px}.device-browser{display:grid;grid-template-columns:minmax(0,1fr) 140px;direction:ltr;gap:4px;min-height:520px}.category-rail{grid-column:2;direction:rtl;position:sticky;top:14px;display:flex;flex-direction:column;align-items:stretch;gap:14px;height:min(720px,calc(100vh - 70px));overflow-y:auto;scroll-snap-type:y mandatory;scrollbar-width:none}.category-rail:before,.category-rail:after{content:"";flex:0 0 calc(50% - 58px)}.category-rail::-webkit-scrollbar{display:none}.category-tab{display:grid;justify-items:center;width:100%;padding:7px 0;border:0;background:transparent;color:var(--muted);cursor:pointer;scroll-snap-align:center;transform:translateX(var(--arc-x,0)) scale(var(--arc-scale,.84));opacity:var(--arc-opacity,.5);transition:.2s;will-change:transform}.category-tab img,.category-icon{display:grid;place-items:center;width:68px;height:68px;border:3px solid rgba(255,255,255,.1);border-radius:50%;object-fit:cover;background:#111a25;font-size:28px}.category-tab span:last-child{width:86px;margin-top:5px;text-align:center;font-size:10px;font-weight:900}.category-tab.active{z-index:4;color:#fff;filter:brightness(1.15)}.category-tab.active img,.category-tab.active .category-icon{border-color:var(--cyan);box-shadow:0 0 0 5px rgba(33,220,255,.12),0 0 34px rgba(33,220,255,.65)}
        .category-content{grid-column:1;grid-row:1;direction:rtl;position:relative;isolation:isolate;min-width:0;min-height:520px;overflow:hidden;border-radius:22px}.category-background{position:absolute;z-index:-2;inset:0;width:100%;height:100%;object-fit:cover;opacity:0;filter:saturate(.82) contrast(1.08);transition:opacity .5s}.category-content.has-video .category-background{opacity:.3}.category-content:after{content:"";position:absolute;z-index:-1;inset:0;background:linear-gradient(90deg,rgba(5,9,14,.72),rgba(5,9,14,.4) 50%,rgba(5,9,14,.78));pointer-events:none}.category-pane[hidden]{display:none}.category-title{display:flex;align-items:center;gap:9px;margin:8px 14px 4px;font-size:20px}.category-title:before{content:"";width:5px;height:25px;border-radius:10px;background:var(--cyan);box-shadow:0 0 13px var(--cyan)}
        .devices{position:relative;min-height:500px}.device{position:absolute;top:0;left:0;display:flex;flex-direction:column;align-items:center;width:180px;min-height:240px;padding:0 5px;cursor:pointer;transform:translate(var(--scatter-x,0),var(--scatter-y,0));transition:transform .4s cubic-bezier(.2,.8,.2,1),filter .25s}.device:hover{transform:translate(var(--scatter-x,0),calc(var(--scatter-y,0) - 6px));filter:brightness(1.08)}.device-portrait{display:grid;place-items:center;width:150px;height:150px;overflow:hidden;border:3px solid rgba(33,220,255,.42);border-radius:50%;background:radial-gradient(circle,rgba(33,220,255,.14),#08101a 70%);box-shadow:0 0 20px rgba(33,220,255,.2),0 12px 26px rgba(0,0,0,.58);transition:.28s}.device-image{display:block;width:82%;height:82%;object-fit:contain;object-position:center;background:transparent;filter:drop-shadow(0 10px 10px rgba(0,0,0,.45));transition:.28s}.device:hover .device-portrait{transform:scale(1.06);border-color:var(--cyan);box-shadow:0 0 34px rgba(33,220,255,.65)}.device:hover .device-image{transform:scale(1.03)}.device-name{display:grid;place-items:center;width:100%;min-height:40px;margin-top:8px;padding:6px 9px;border:1px solid var(--border);border-radius:11px;background:rgba(0,0,0,.9);font-size:13px;font-weight:900;text-align:center}.device-meta{margin-top:4px;color:var(--muted);font-size:10px}.device-price{color:var(--cyan);font-size:14px;font-weight:900}.device-actions{position:absolute!important;z-index:12!important;top:-7px;left:3px;display:flex;pointer-events:auto!important}.circle-action{position:relative;z-index:13;display:grid;place-items:center;width:38px;height:38px;padding:0;border:2px solid rgba(33,220,255,.72);border-radius:50%;background:rgba(0,0,0,.9);color:var(--cyan);cursor:pointer;pointer-events:auto!important;touch-action:manipulation}.circle-action:hover,.circle-action.selected{background:var(--cyan);color:#00131c;box-shadow:0 0 20px rgba(33,220,255,.7)}.empty{display:grid;place-items:center;min-height:350px;color:var(--muted);text-align:center}.pagination{margin-top:18px}.pagination nav{display:flex;justify-content:center}
        .compare-bar{position:fixed;z-index:40;right:18px;bottom:18px;left:18px;display:none;align-items:center;gap:12px;max-width:1050px;margin:auto;padding:12px 14px;border:1px solid rgba(33,220,255,.38);border-radius:20px;background:rgba(8,15,25,.94);box-shadow:0 18px 60px #000,0 0 26px rgba(33,220,255,.12);backdrop-filter:blur(18px)}.compare-bar.show{display:flex;animation:compareIn .25s ease}.compare-summary{white-space:nowrap}.compare-summary strong{display:block;color:var(--cyan)}.compare-summary small{color:var(--muted)}.compare-list{display:flex;gap:8px;overflow:auto;flex:1}.compare-item{display:flex;align-items:center;gap:8px;min-width:175px;padding:6px 8px;border:1px solid var(--border);border-radius:12px;background:#101a27;font-size:11px}.compare-item img{width:38px;height:38px;object-fit:contain}.compare-remove{margin-right:auto;border:0;background:transparent;color:#ff7c8f;cursor:pointer}.compare-primary,.compare-clear,.compare-close{border:0;cursor:pointer}.compare-primary{padding:11px 17px;border-radius:12px;background:linear-gradient(135deg,var(--cyan),#6985ff);color:#00131c;font-weight:900}.compare-primary:disabled{cursor:not-allowed;filter:grayscale(.7);opacity:.55}.compare-clear{padding:9px;color:#b8c8d4;background:transparent}.compare-modal{position:fixed;z-index:80;inset:0;display:none;padding:24px;background:rgba(0,3,8,.82);backdrop-filter:blur(15px)}.compare-modal.open{display:grid;place-items:center}.compare-dialog{width:min(1120px,100%);max-height:calc(100vh - 48px);overflow:auto;border:1px solid rgba(33,220,255,.35);border-radius:26px;background:linear-gradient(145deg,#0c1521,#070b12);box-shadow:0 30px 100px #000}.compare-head{position:sticky;z-index:4;top:0;display:flex;align-items:center;justify-content:space-between;padding:18px 22px;border-bottom:1px solid var(--border);background:rgba(9,15,24,.96);backdrop-filter:blur(15px)}.compare-head h2{margin:0}.compare-close{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#172332;color:#fff;font-size:22px}.compare-table-wrap{overflow-x:auto;padding:10px 20px 24px}.compare-table{width:100%;min-width:680px;border-collapse:separate;border-spacing:0 8px;table-layout:fixed}.compare-table th,.compare-table td{padding:12px;text-align:center;background:#101a27}.compare-table th:first-child,.compare-table td:first-child{width:150px;border-radius:0 12px 12px 0;color:var(--muted);text-align:right}.compare-table th:last-child,.compare-table td:last-child{border-radius:12px 0 0 12px}.compare-product img{display:block;width:105px;height:105px;margin:0 auto 8px;object-fit:contain}.compare-product b{display:block;font-size:15px}.compare-product a{display:inline-block;margin-top:8px;color:var(--cyan);font-size:11px}.compare-table tr.different td:not(:first-child){box-shadow:inset 0 -2px rgba(33,220,255,.32)}body.compare-open{overflow:hidden}@keyframes compareIn{from{opacity:0;transform:translateY(20px)}}
        @media(max-width:1100px){.hero-content{grid-template-columns:1fr;min-height:330px}.hero-webgl{position:absolute;left:0;bottom:0;opacity:.48;width:330px}.filters{grid-template-columns:repeat(3,minmax(0,1fr))}.filters input:first-child{grid-column:1/-1}.devices{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:34px 14px;height:auto!important;padding:20px 10px}.device{position:relative;inset:auto;width:100%;min-height:235px;transform:none!important;justify-self:center}}
        @media(max-width:720px){html,body{width:100%;max-width:100%;overflow-x:hidden}.wrap{width:100%;padding-inline:10px}.hero{min-height:290px;border-radius:0 0 24px 24px}.hero-content{min-height:270px;padding:22px 12px}.hero h1{font-size:clamp(34px,12vw,48px);margin:14px 0 10px}.hero p{max-width:72%;font-size:12px;line-height:1.65}.hero-kicker{font-size:10px}.hero-webgl{left:-72px;width:260px;height:260px}.filters{grid-template-columns:1fr 1fr;margin:-12px 0 16px;padding:9px}.filters input:first-child,.filters button{grid-column:1/-1}.filters input,.filters select,.filters button{height:44px;font-size:12px}.catalog{min-height:0;margin-bottom:80px;padding:13px 7px;border-radius:20px}.catalog-head{padding-inline:6px}.catalog-head h2{font-size:22px}.device-browser{grid-template-columns:minmax(0,1fr) 88px;gap:0;min-height:0}.category-rail{height:calc(100dvh - 72px);gap:9px}.category-rail:before,.category-rail:after{flex-basis:calc(50% - 48px)}.category-tab img,.category-icon{width:54px;height:54px}.category-tab span:last-child{width:65px;font-size:9px}.category-content{min-height:460px;border-radius:16px}.category-title{margin-inline:8px;font-size:17px}.devices{grid-template-columns:repeat(2,minmax(0,1fr));gap:28px 4px;padding:15px 2px}.device{width:100%;min-width:0;min-height:190px}.device-portrait{width:min(108px,30vw);height:min(108px,30vw)}.device-image{width:82%;height:82%}.device-name{width:min(125px,100%);min-height:34px;font-size:10px}.device-meta{font-size:8px;text-align:center}.device-price{font-size:11px}.device-actions{left:max(0px,calc(50% - 60px))}.circle-action{width:34px;height:34px}.compare-bar{right:7px;bottom:7px;left:7px;flex-wrap:wrap;padding:8px}.compare-summary{display:block;width:100%}.compare-list{width:100%;order:-1}.compare-item{min-width:140px}.compare-primary{flex:1}.compare-modal{padding:6px}.compare-dialog{max-height:calc(100dvh - 12px);border-radius:16px}.compare-head{padding:12px}.compare-table-wrap{padding:4px 7px 14px}}
        @media(max-width:390px){.device-browser{grid-template-columns:minmax(0,1fr) 76px}.devices{grid-template-columns:1fr}.device-portrait{width:124px;height:124px}.device-actions{left:calc(50% - 70px)}}
        /* Premium storefront hero */
        .hero{min-height:330px;border-radius:0 0 32px 32px;background:radial-gradient(circle at 18% 45%,rgba(121,86,255,.16),transparent 27%),radial-gradient(circle at 82% 18%,rgba(33,220,255,.13),transparent 29%),linear-gradient(120deg,#050a12,#081521)}.hero:after{inset:0;background-image:linear-gradient(rgba(33,220,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(33,220,255,.035) 1px,transparent 1px);background-size:54px 54px;transform:none;mask-image:linear-gradient(to bottom,transparent,#000)}.hero-content{grid-template-columns:minmax(0,1.15fr) minmax(290px,.7fr);min-height:305px;gap:46px;padding-block:26px}.hero h1{font-size:clamp(42px,5vw,65px);margin:14px 0 9px}.hero p{margin:0;font-size:16px}.hero-kicker{font-size:11px}.hero-actions{display:flex;align-items:center;gap:12px;margin-top:17px}.hero-cta{padding:10px 17px;border-radius:12px;background:linear-gradient(135deg,var(--cyan),#6985ff);color:#00131c;font-size:12px;font-weight:900}.hero-note{color:var(--muted);font-size:10px}.hero-showcase{position:relative;justify-self:center;display:grid;grid-template-columns:145px 1fr;align-items:center;width:min(330px,100%);min-height:205px;padding:17px;border:1px solid rgba(33,220,255,.28);border-radius:27px;background:linear-gradient(145deg,rgba(17,30,45,.82),rgba(7,12,20,.9));box-shadow:0 25px 65px rgba(0,0,0,.45);backdrop-filter:blur(18px)}.hero-showcase:before{content:"";position:absolute;left:18px;width:155px;height:155px;border-radius:50%;background:radial-gradient(circle,rgba(33,220,255,.22),transparent 69%)}.hero-showcase img{position:relative;width:145px;height:175px;object-fit:contain;filter:drop-shadow(0 18px 18px rgba(0,0,0,.6))}.showcase-copy{position:relative;padding-right:10px}.showcase-copy small{color:var(--cyan);font-size:9px}.showcase-copy b{display:block;margin:5px 0;font-size:15px}.showcase-copy span{color:var(--muted);font-size:9px}.showcase-placeholder{display:grid;place-items:center;width:145px;height:145px;color:var(--cyan);font-size:42px}.filters{margin-top:-17px;padding:11px;border-radius:16px}
        @media(max-width:900px){.hero-content{grid-template-columns:1fr minmax(230px,.6fr);gap:20px}.hero-showcase{grid-template-columns:110px 1fr;width:255px;min-height:170px;padding:12px}.hero-showcase img,.showcase-placeholder{width:110px;height:140px}.hero-showcase:before{width:115px;height:115px}}
        @media(max-width:720px){.hero{min-height:355px}.hero-content{display:block;min-height:335px;padding-bottom:105px}.hero p{max-width:100%}.hero-actions{margin-top:12px}.hero-showcase{position:absolute;left:10px;bottom:20px;grid-template-columns:78px 1fr;width:190px;min-height:92px;padding:7px;border-radius:18px}.hero-showcase img,.showcase-placeholder{width:78px;height:82px}.hero-showcase:before{width:78px;height:78px}.showcase-copy b{font-size:11px}.showcase-copy span{display:none}.filters{margin-top:-12px}}
        .hero-showcase{display:block;overflow:hidden}.hero-slide{display:none;grid-template-columns:145px 1fr;align-items:center;color:#fff}.hero-slide.active{display:grid;animation:heroSlideIn .45s ease}.showcase-price{display:block!important;margin-top:8px;color:var(--cyan)!important;font-size:12px!important;font-weight:900}.hero-controls{position:absolute;z-index:5;right:12px;bottom:8px;left:12px;display:flex;align-items:center;justify-content:space-between}.hero-arrow{display:grid;place-items:center;width:27px;height:27px;padding:0;border:1px solid rgba(33,220,255,.3);border-radius:50%;background:rgba(4,9,15,.78);color:var(--cyan);cursor:pointer}.hero-dots{display:flex;gap:4px}.hero-dot{width:5px;height:5px;padding:0;border:0;border-radius:8px;background:#526777;cursor:pointer;transition:.25s}.hero-dot.active{width:17px;background:var(--cyan)}@keyframes heroSlideIn{from{opacity:0;transform:translateX(-16px)}}
        @media(max-width:900px){.hero-slide{grid-template-columns:110px 1fr}}
        @media(max-width:720px){.hero-showcase{width:205px;min-height:100px;padding-bottom:22px}.hero-slide{grid-template-columns:78px 1fr}.showcase-copy span.showcase-price{display:block;font-size:9px!important}.hero-controls{right:6px;bottom:3px;left:6px}.hero-arrow{width:21px;height:21px;font-size:10px}}
        .category-content{background:radial-gradient(circle at 35% 40%,rgba(33,220,255,.07),transparent 32%),#060b12}.category-background{inset:-2%;width:104%;height:104%;filter:saturate(.9) contrast(1.12) brightness(.72);transform:scale(1.025);transition:opacity .7s ease,transform 8s ease}.category-content.has-video .category-background{opacity:.52;transform:scale(1)}.category-content.has-video:after{background:linear-gradient(90deg,rgba(5,9,14,.82),rgba(5,9,14,.35) 48%,rgba(5,9,14,.72)),linear-gradient(0deg,rgba(5,9,14,.72),transparent 40%,rgba(5,9,14,.35))}@media(max-width:720px){.category-content.has-video .category-background{opacity:.4}}
        .catalog-pagination{display:flex;align-items:center;justify-content:center;gap:7px;flex-wrap:wrap;margin:24px auto 2px;padding:12px}.page-link,.page-current,.page-disabled{display:grid;place-items:center;min-width:40px;height:40px;padding:0 12px;border:1px solid #263b4e;border-radius:11px;background:#101925;color:#c8d6df;font-size:12px;font-weight:800}.page-link:hover{border-color:var(--cyan);color:var(--cyan);box-shadow:0 0 16px rgba(33,220,255,.16)}.page-current{border-color:var(--cyan);background:linear-gradient(135deg,var(--cyan),#6985ff);color:#00131c}.page-disabled{opacity:.35}.page-results{width:100%;color:var(--muted);font-size:10px;text-align:center}@media(max-width:720px){.catalog-pagination{gap:5px;margin-top:16px;padding:8px}.page-link,.page-current,.page-disabled{min-width:34px;height:34px;padding:0 9px;font-size:10px}}
        .category-pagination{position:relative;z-index:4;margin-top:8px}.category-pagination .page-results{width:auto;min-width:90px}.category-pagination button:disabled{opacity:.3;cursor:not-allowed}
        @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}.category-background{display:none}}
    </style>
</head>
<body>
@php
    $bannerUrl = $shop->banner ? (\Illuminate\Support\Str::startsWith($shop->banner,['http://','https://','storage/']) ? asset($shop->banner) : asset('storage/'.$shop->banner)) : '';
    $listedProducts = $products;
    $categoryItems = $categories->map(fn($category) => [
        'key' => (string)$category->id,
        'name' => $category->localized('name'),
        'image' => $category->image ?: $listedProducts->first(fn($product) => $product->category_id === $category->id && filled($product->main_image))?->main_image,
        'background' => $category->background_video,
        'products' => $listedProducts->where('category_id',$category->id)->values(),
    ]);
    $uncategorized = $listedProducts->whereNull('category_id')->values();
    if($uncategorized->isNotEmpty()) $categoryItems->push(['key'=>'other','name'=>'أجهزة أخرى','image'=>$uncategorized->first()?->main_image,'background'=>null,'products'=>$uncategorized]);
    $requestedCategory = (string)request('category','');
    $activeKey = $categoryItems->contains(fn($item)=>$item['key']===$requestedCategory) ? $requestedCategory : (string)($categoryItems->first()['key'] ?? '');
    $mediaUrl = fn($path) => filled($path) ? (\Illuminate\Support\Str::startsWith($path,['http://','https://','storage/']) ? asset($path) : asset('storage/'.$path)) : '';
@endphp
<header class="hero" style="--hero-image:url('{{ $bannerUrl }}')">
    <div class="wrap hero-content"><div><span class="hero-kicker">● تجربة تسوق تقنية متكاملة</span><h1>{{ $shop->name }}</h1><p>{{ $shop->description ?: 'اكتشف أحدث الأجهزة، قارن المواصفات والأسعار، واختر الجهاز الأنسب لك.' }}</p><div class="hero-actions"><a class="hero-cta" href="#devicesCatalog">استكشف الأجهزة</a><span class="hero-note">مواصفات واضحة وأسعار مباشرة</span></div></div>@if($heroDevices->isNotEmpty())<div class="hero-showcase" id="heroShowcase">@foreach($heroDevices as $heroIndex=>$heroDevice)@php $heroPrice=$heroDevice->variants->where('quantity','>',0)->min(fn($variant)=>(float)($variant->price??$heroDevice->discount_price??$heroDevice->price))??$heroDevice->discount_price??$heroDevice->price; @endphp<a class="hero-slide @if($heroIndex===0) active @endif" href="{{ route('electronics.product',[$shop,$heroDevice]) }}" data-hero-slide><div>@if($heroDevice->main_image)<img src="{{ $mediaUrl($heroDevice->main_image) }}" alt="{{ $heroDevice->localized('name') }}">@else<span class="showcase-placeholder"><i class="ti ti-device-mobile"></i></span>@endif</div><div class="showcase-copy"><small>جهاز {{ $heroIndex+1 }} من {{ $heroDevices->count() }}</small><b>{{ $heroDevice->localized('name') }}</b><span>شاهد المواصفات والخيارات المتوفرة ←</span><span class="showcase-price">من {{ number_format((float)$heroPrice,2) }} ₪</span></div></a>@endforeach @if($heroDevices->count()>1)<div class="hero-controls"><button type="button" class="hero-arrow" id="heroPrev" aria-label="السابق">‹</button><div class="hero-dots">@foreach($heroDevices as $heroIndex=>$heroDevice)<button type="button" class="hero-dot @if($heroIndex===0) active @endif" data-hero-dot="{{ $heroIndex }}" aria-label="الجهاز {{ $heroIndex+1 }}"></button>@endforeach</div><button type="button" class="hero-arrow" id="heroNext" aria-label="التالي">›</button></div>@endif</div>@endif</div>
</header>
<main class="wrap">
    <form class="filters" method="GET">
        <input name="q" value="{{ request('q') }}" placeholder="ابحث عن جهاز أو موديل...">
        <select name="brand"><option value="">كل الماركات</option>@foreach($brands as $brand)<option @selected(request('brand')===$brand)>{{ $brand }}</option>@endforeach</select>
        <select name="storage"><option value="">كل السعات</option>@foreach($storages as $storage)<option @selected(request('storage')===$storage)>{{ $storage }}</option>@endforeach</select>
        <select name="condition"><option value="">جديد ومستعمل</option><option @selected(request('condition')==='جديد')>جديد</option><option @selected(request('condition')==='مستعمل')>مستعمل</option></select>
        <input type="number" name="min_price" value="{{ request('min_price') }}" placeholder="أقل سعر">
        <input type="number" name="max_price" value="{{ request('max_price') }}" placeholder="أعلى سعر">
        <button>تصفية</button>
    </form>
    <section class="catalog" id="devicesCatalog">
        <header class="catalog-head"><div><h2>الأجهزة</h2><p>اختر الفئة ثم اضغط على الجهاز لعرض التفاصيل والشراء.</p></div></header>
        @if($categoryItems->isNotEmpty())
            <div class="device-browser">
                <nav class="category-rail" id="categoryRail" aria-label="فئات الأجهزة">
                    @foreach($categoryItems as $category)
                        <button type="button" class="category-tab @if($category['key']===$activeKey) active @endif" data-category-key="{{ $category['key'] }}">
                            @if($category['image'])<img src="{{ $mediaUrl($category['image']) }}" alt="" loading="lazy">@else<span class="category-icon"><i class="ti ti-device-mobile"></i></span>@endif
                            <span>{{ $category['name'] }}</span>
                        </button>
                    @endforeach
                </nav>
                <div class="category-content" id="categoryContent">
                    <video class="category-background" id="categoryBackground" autoplay muted loop playsinline preload="metadata" aria-hidden="true"></video>
                    @foreach($categoryItems as $category)
                        <section class="category-pane" data-category-pane="{{ $category['key'] }}" @if($category['background']) data-background-video="{{ $mediaUrl($category['background']) }}" @endif @if($category['image']) data-background-poster="{{ $mediaUrl($category['image']) }}" @endif @if($category['key']!==$activeKey) hidden @endif>
                            <h3 class="category-title">{{ $category['name'] }}</h3>
                            <div class="devices">
                                @forelse($category['products'] as $product)
                                    @php
                                        $attrs=$product->catalog_attributes??[];$available=$product->variants->where('quantity','>',0);
                                        $from=$available->min(fn($variant)=>(float)($variant->price??$product->discount_price??$product->price));
                                        $compare=['id'=>$product->id,'name'=>$product->localized('name'),'image'=>$mediaUrl($product->main_image) ?: asset('images/logo.svg'),'url'=>route('electronics.product',[$shop,$product]),'brand'=>data_get($attrs,'brand'),'model'=>data_get($attrs,'model'),'condition'=>data_get($attrs,'condition'),'network'=>data_get($attrs,'network'),'screen'=>data_get($attrs,'screen_size'),'processor'=>data_get($attrs,'processor'),'battery'=>data_get($attrs,'battery'),'battery_health'=>data_get($attrs,'battery_health'),'cameras'=>data_get($attrs,'cameras'),'warranty'=>data_get($attrs,'warranty_months'),'storage'=>$available->pluck('storage')->filter()->unique()->values()->implode('، '),'ram'=>$available->pluck('ram')->filter()->unique()->values()->implode('، '),'colors'=>$available->pluck('color_name')->filter()->unique()->values()->implode('، '),'price'=>$from];
                                    @endphp
                                    <article class="device" data-device data-local-page="{{ intdiv($loop->index,12)+1 }}" @if($loop->index>=12) hidden @endif data-compare="{{ e(json_encode($compare,JSON_UNESCAPED_UNICODE)) }}" tabindex="0">
                                        <form class="device-actions" method="POST" action="{{ route('electronics.compare.toggle', [$shop, $product]) }}">@csrf<button type="submit" class="circle-action compare @if($comparisonProducts->contains('id',$product->id)) selected @endif" aria-label="@if($comparisonProducts->contains('id',$product->id)) إزالة من المقارنة @else إضافة للمقارنة @endif"><i class="ti ti-arrows-diff"></i></button></form>
                                        <a href="{{ route('electronics.product',[$shop,$product]) }}"><span class="device-portrait"><img class="device-image" src="{{ $mediaUrl($product->main_image) ?: asset('images/logo.svg') }}" alt="{{ $product->localized('name') }}" loading="lazy"></span><span class="device-name">{{ $product->localized('name') }}</span><div class="device-meta">{{ data_get($attrs,'brand') }} · {{ data_get($attrs,'condition') }}</div><div class="device-price">من {{ number_format((float)$from,2) }} ₪</div></a>
                                    </article>
                                @empty<div class="empty"><div><i class="ti ti-device-mobile-off" style="font-size:44px"></i><br>لا توجد أجهزة في هذه الفئة ضمن نتائج البحث الحالية.</div></div>@endforelse
                            </div>
                            @if($category['products']->count()>12)<nav class="catalog-pagination category-pagination" data-category-pagination aria-label="صفحات {{ $category['name'] }}"><button type="button" class="page-link" data-page-move="-1">السابق</button><span class="page-results" data-page-status></span><div style="display:flex;gap:5px" data-page-numbers></div><button type="button" class="page-link" data-page-move="1">التالي</button></nav>@endif
                        </section>
                    @endforeach
                </div>
            </div>
        @else<div class="empty">لا توجد فئات أو أجهزة مطابقة للفلاتر.</div>@endif
    </section>
</main>
@if($comparisonProducts->isNotEmpty())
<aside class="compare-bar show" id="compareBar" aria-live="polite"><div class="compare-summary"><strong>المقارنة</strong><small>{{ $comparisonProducts->count() === 1 ? 'اختر جهازاً آخر' : $comparisonProducts->count().' من 3 أجهزة' }}</small></div><div class="compare-list">@foreach($comparisonProducts as $item)<div class="compare-item"><img src="{{ $mediaUrl($item->main_image) ?: asset('images/logo.svg') }}" alt=""><span><b>{{ $item->localized('name') }}</b></span></div>@endforeach</div><form method="POST" action="{{ route('electronics.compare.clear',$shop) }}">@csrf<button type="submit" class="compare-clear">مسح الكل</button></form>@if($comparisonProducts->count() >= 2)<a class="compare-primary" href="{{ route('electronics.compare',$shop) }}">قارن الآن</a>@else<button type="button" class="compare-primary" disabled>اختر جهازاً آخر</button>@endif</aside>
@endif
<script>
(()=>{
 const rail=document.getElementById('categoryRail'),tabs=[...document.querySelectorAll('.category-tab')],panes=[...document.querySelectorAll('[data-category-pane]')],content=document.getElementById('categoryContent'),video=document.getElementById('categoryBackground');let active=document.querySelector('.category-tab.active')?.dataset.categoryKey,frame;
 const hash=v=>[...String(v)].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619)>>>0,2166136261),rng=s=>()=>{s=Math.imul(s^s>>>15,s|1);s^=s+Math.imul(s^s>>>7,s|61);return((s^s>>>14)>>>0)/4294967296};
 const arc=()=>{if(!rail)return;const box=rail.getBoundingClientRect(),center=box.top+box.height/2,reach=Math.max(1,box.height/2);tabs.forEach(tab=>{const b=tab.getBoundingClientRect(),d=Math.min(1,Math.abs(b.top+b.height/2-center)/reach),curve=Math.cos(d*Math.PI/2);tab.style.setProperty('--arc-x',`${-(innerWidth<=720?14:22)*curve}px`);tab.style.setProperty('--arc-scale',String(.78+curve*.52));tab.style.setProperty('--arc-opacity',String(.38+curve*.62))})};
 const scatter=pane=>{const area=pane?.querySelector('.devices'),cards=[...(area?.querySelectorAll('.device:not([hidden])')||[])];if(!area||!cards.length||innerWidth<=720)return;const width=area.clientWidth;if(!width)return;const cw=180,ch=240,cols=Math.max(1,Math.floor(width/215)),rows=Math.max(2,Math.ceil(cards.length/cols)),height=Math.max(500,rows*270),random=rng(hash(`${pane.dataset.categoryPane}-${pane.dataset.currentPage||1}`)),slots=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)slots.push({r,c});for(let i=slots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[slots[i],slots[j]]=[slots[j],slots[i]]}cards.forEach((card,i)=>{const s=slots[i],cellW=width/cols,cellH=height/rows,x=s.c*cellW+Math.max(0,cellW-cw)*(.15+random()*.7),y=s.r*cellH+Math.max(0,cellH-ch)*random();card.style.setProperty('--scatter-x',`${Math.round(x)}px`);card.style.setProperty('--scatter-y',`${Math.round(y)}px`)});area.style.height=`${height}px`};
 const background=pane=>{if(!video||!content)return;const src=pane?.dataset.backgroundVideo||'',poster=pane?.dataset.backgroundPoster||'';if(poster)video.poster=poster;else video.removeAttribute('poster');if(!src){content.classList.remove('has-video');video.pause();video.removeAttribute('src');video.load();return}if(video.getAttribute('src')!==src){content.classList.remove('has-video');video.src=src;video.load()}video.play().then(()=>content.classList.add('has-video')).catch(()=>{})};
 const setCategoryPage=(pane,page)=>{const cards=[...pane.querySelectorAll('.device[data-local-page]')],total=Math.max(1,...cards.map(card=>Number(card.dataset.localPage)||1)),next=Math.max(1,Math.min(total,page));pane.dataset.currentPage=String(next);cards.forEach(card=>card.hidden=Number(card.dataset.localPage)!==next);const pager=pane.querySelector('[data-category-pagination]');if(pager){pager.querySelector('[data-page-status]').textContent=`صفحة ${next} من ${total}`;pager.querySelector('[data-page-move="-1"]').disabled=next===1;pager.querySelector('[data-page-move="1"]').disabled=next===total;pager.querySelector('[data-page-numbers]').innerHTML=Array.from({length:total},(_,index)=>`<button type="button" class="${index+1===next?'page-current':'page-link'}" data-page-number="${index+1}">${index+1}</button>`).join('')}requestAnimationFrame(()=>scatter(pane))};
 panes.forEach(pane=>{pane.dataset.currentPage='1';setCategoryPage(pane,1);pane.querySelector('[data-category-pagination]')?.addEventListener('click',event=>{const number=event.target.closest('[data-page-number]'),move=event.target.closest('[data-page-move]');if(number)setCategoryPage(pane,Number(number.dataset.pageNumber));else if(move)setCategoryPage(pane,Number(pane.dataset.currentPage)+Number(move.dataset.pageMove))})});
 const activate=(key,center=false)=>{if(!key)return;active=key;tabs.forEach(tab=>{const on=tab.dataset.categoryKey===key;tab.classList.toggle('active',on);if(on&&center)tab.scrollIntoView({behavior:'smooth',block:'center'})});panes.forEach(p=>p.hidden=p.dataset.categoryPane!==key);const pane=panes.find(p=>p.dataset.categoryPane===key);background(pane);requestAnimationFrame(()=>scatter(pane))};
 tabs.forEach(tab=>tab.onclick=()=>activate(tab.dataset.categoryKey,true));rail?.addEventListener('scroll',()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{arc();const b=rail.getBoundingClientRect(),center=b.top+b.height/2,closest=tabs.reduce((best,t)=>{const r=t.getBoundingClientRect(),d=Math.abs(r.top+r.height/2-center);return!best||d<best.d?{t,d}:best},null);if(closest&&closest.t.dataset.categoryKey!==active)activate(closest.t.dataset.categoryKey)})},{passive:true});
 video?.addEventListener('canplay',()=>{content.classList.add('has-video');video.play().catch(()=>{})});addEventListener('resize',()=>{arc();scatter(panes.find(p=>!p.hidden))},{passive:true});requestAnimationFrame(()=>{arc();const pane=panes.find(p=>!p.hidden);scatter(pane);background(pane)});
})();
</script>
<script>
(()=>{const box=document.getElementById('heroShowcase'),slides=[...document.querySelectorAll('[data-hero-slide]')],dots=[...document.querySelectorAll('[data-hero-dot]')];if(!box||slides.length<2)return;let current=0,timer;const show=index=>{current=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle('active',i===current));dots.forEach((dot,i)=>dot.classList.toggle('active',i===current))},play=()=>{clearInterval(timer);timer=setInterval(()=>show(current+1),3000)};document.getElementById('heroPrev').onclick=event=>{event.preventDefault();show(current-1);play()};document.getElementById('heroNext').onclick=event=>{event.preventDefault();show(current+1);play()};dots.forEach((dot,index)=>dot.onclick=event=>{event.preventDefault();show(index);play()});document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInterval(timer);else play()});play()})();
</script>
</body>
</html>
