<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $product->localized('name') }} | {{ $shop->name }}</title>
<style>*{box-sizing:border-box}body{margin:0;background:#070a10;color:#f6f8fb;font-family:Cairo,Segoe UI,sans-serif}a{color:#61dafb}.wrap{width:min(1180px,calc(100% - 28px));margin:auto}.top{padding:18px 0}.product{display:grid;grid-template-columns:1fr 1fr;gap:28px;background:#0d141e;border:1px solid #1c3041;border-radius:28px;padding:24px}.main-img{width:100%;aspect-ratio:1/1;object-fit:contain;background:#fff;border-radius:20px}.thumbs{display:flex;gap:8px;margin-top:10px;overflow:auto}.thumbs img{width:74px;height:74px;object-fit:cover;background:#fff;border-radius:12px;cursor:pointer;border:2px solid transparent}.eyebrow{color:#61dafb}.info h1{font-size:clamp(28px,5vw,48px);margin:8px 0}.tags{display:flex;gap:7px;flex-wrap:wrap}.tag{padding:7px 10px;background:#172432;border-radius:9px;color:#c5d7e3}.price{font-size:34px;font-weight:900;margin:20px 0}.options{display:grid;gap:12px}.option{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:8px;align-items:center;padding:12px;border:1px solid #284157;border-radius:14px;cursor:pointer}.option:has(input:checked){border-color:#61dafb;background:#102331}.option.sold{opacity:.45;cursor:not-allowed}.buy{margin-top:20px;display:grid;gap:10px}.buy input,.buy textarea,.buy button{width:100%;border:1px solid #294156;background:#111c28;color:#fff;border-radius:13px;padding:13px}.buy button{background:#20b7e8;color:#00141c;font-weight:900;font-size:16px}.spec-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:26px 0}.spec{background:#0d141e;border:1px solid #1c3041;border-radius:14px;padding:14px}.spec small{display:block;color:#7991a3}.related{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:50px}.related a{background:#0d141e;padding:12px;border-radius:14px}.related img{width:100%;aspect-ratio:1;object-fit:contain;background:#fff;border-radius:10px}@media(max-width:760px){.product{grid-template-columns:1fr;padding:15px}.option{grid-template-columns:1fr 1fr}.spec-grid{grid-template-columns:1fr 1fr}.related{grid-template-columns:1fr 1fr}}</style></head>
<body><div class="wrap"><div class="top"><a href="{{ route('electronics.store',$shop) }}">← العودة إلى {{ $shop->name }}</a></div>
@php
    $attrs = $product->catalog_attributes ?? [];
    $resolveImage = fn ($path) => $path
        ? (\Illuminate\Support\Str::startsWith($path, ['http://', 'https://', 'storage/']) ? asset($path) : asset('storage/'.$path))
        : asset('images/1.jpg');
@endphp
<main class="product"><section><img class="main-img" id="mainImage" src="{{ $resolveImage($product->main_image) }}"><div class="thumbs"><img src="{{ $resolveImage($product->main_image) }}">@foreach($product->images as $image)<img src="{{ $resolveImage($image->image) }}">@endforeach</div></section>
<section class="info"><div class="eyebrow">{{ data_get($attrs,'brand') }} · {{ data_get($attrs,'model') }}</div><h1>{{ $product->localized('name') }}</h1><div class="tags"><span class="tag">{{ data_get($attrs,'condition') }}</span><span class="tag">{{ data_get($attrs,'network') }}</span><span class="tag">{{ data_get($attrs,'screen_size') }}</span><span class="tag">{{ data_get($attrs,'sim_type') }}</span></div><p>{{ $product->localized('description') }}</p><div class="price" id="price">اختر التخزين واللون</div>
<div class="options">@foreach($product->variants as $variant)<label class="option {{ $variant->quantity<1?'sold':'' }}"><input type="radio" name="variant" value="{{ $variant->id }}" data-price="{{ (float)($variant->price??$product->discount_price??$product->price) }}" @disabled($variant->quantity<1)><b>{{ $variant->storage ?: 'قياسي' }}</b><span>{{ $variant->ram ? 'RAM '.$variant->ram : '' }}</span><span title="{{ $variant->color }}" style="display:inline-flex;align-items:center;gap:7px"><i style="display:inline-block;width:24px;height:24px;border-radius:50%;background:{{ $variant->color }};border:2px solid rgba(255,255,255,.7);box-shadow:0 0 0 1px rgba(0,0,0,.5)"></i>{{ $variant->color }}</span><small>{{ $variant->quantity>0 ? $variant->quantity.' متوفر' : 'نفد' }}</small></label>@endforeach</div>
<form class="buy" id="buyForm"><input name="customer_name" placeholder="الاسم الكامل" required><input name="customer_phone" placeholder="رقم الجوال" required><textarea name="customer_address" placeholder="عنوان التوصيل" required></textarea><textarea name="customer_notes" placeholder="ملاحظات اختيارية"></textarea><input type="number" name="qty" min="1" max="20" value="1"><button>تأكيد الطلب أونلاين</button><div id="message"></div></form></section></main>
<section class="spec-grid">@foreach(['processor'=>'المعالج','battery'=>'البطارية','cameras'=>'الكاميرات','battery_health'=>'صحة البطارية','warranty_months'=>'الضمان بالأشهر','included_accessories'=>'الملحقات','condition_notes'=>'حالة الجهاز'] as $key=>$label)@if(filled(data_get($attrs,$key)))<div class="spec"><small>{{ $label }}</small>{{ is_array(data_get($attrs,$key))?implode('، ',data_get($attrs,$key)):data_get($attrs,$key) }}</div>@endif @endforeach</section>
<h2>أجهزة مشابهة</h2><section class="related">@foreach($related as $item)<a href="{{ route('electronics.product',[$shop,$item]) }}"><img src="{{ $resolveImage($item->main_image) }}"><b>{{ $item->localized('name') }}</b></a>@endforeach</section></div>
<script>document.querySelectorAll('.thumbs img').forEach(img=>img.onclick=()=>mainImage.src=img.src);document.querySelectorAll('[name=variant]').forEach(v=>v.onchange=()=>price.textContent=Number(v.dataset.price).toFixed(2)+' ₪');buyForm.onsubmit=async e=>{e.preventDefault();const variant=document.querySelector('[name=variant]:checked'),message=document.getElementById('message');if(!variant){message.textContent='اختر التخزين واللون أولاً.';return}const fd=new FormData(buyForm),payload={customer_name:fd.get('customer_name'),customer_phone:fd.get('customer_phone'),customer_address:fd.get('customer_address'),customer_notes:fd.get('customer_notes'),items:[{variant_id:Number(variant.value),qty:Number(fd.get('qty'))}]};const res=await fetch(@json(route('electronics.orders.store',$shop)),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:JSON.stringify(payload)});const data=await res.json();message.textContent=res.ok?'تم تسجيل طلبك: '+data.order_number:(data.message||'تعذر تسجيل الطلب');if(res.ok)buyForm.reset()};</script></body></html>
