<!doctype html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    @php
        $productName = $product->localized('name');
        $productDescription = $product->localized('description') ?: "اشترِ {$productName} من {$shop->name} عبر Ozman.";
        $productCanonical = route('electronics.product', [$shop, $product]);
        $productImage = $product->main_image
            ? asset(\Illuminate\Support\Str::startsWith($product->main_image, 'storage/') ? $product->main_image : 'storage/'.$product->main_image)
            : asset('images/logo.svg');
        $productPrice = $product->discount_price ?: $product->price;
    @endphp
    @include('front.partials.seo', [
        'title' => $productName.' | '.$shop->name,
        'description' => $productDescription,
        'canonical' => $productCanonical,
        'image' => $productImage,
        'type' => 'product',
        'schema' => [
            '@context' => 'https://schema.org', '@type' => 'Product', 'name' => $productName,
            'description' => $productDescription, 'image' => [$productImage], 'sku' => $product->sku,
            'offers' => ['@type' => 'Offer', 'url' => $productCanonical, 'priceCurrency' => 'ILS',
                'price' => $productPrice, 'availability' => $product->quantity > 0 ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock'],
        ],
    ])
    <style>
        :root{--cyan:#22d8ff;--blue:#599cff;--panel:#0d141f;--line:#203347;--muted:#91a7b7}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 80% 0,rgba(34,216,255,.08),transparent 28%),#060910;color:#f7f9fc;font-family:Cairo,"Segoe UI",sans-serif}button,input,textarea{font:inherit}a{color:inherit;text-decoration:none}.wrap{width:min(1180px,calc(100% - 28px));margin:auto}.top{height:72px;display:flex;align-items:center;justify-content:space-between}.back{display:inline-flex;align-items:center;gap:8px;color:#bdeeff}.store-name{font-weight:900;color:var(--cyan)}
        .product{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(360px,.95fr);gap:26px;background:linear-gradient(145deg,rgba(15,24,37,.96),rgba(7,11,18,.98));border:1px solid var(--line);border-radius:30px;padding:22px;box-shadow:0 35px 100px rgba(0,0,0,.4)}.media-stage{position:relative;display:grid;place-items:center;height:560px;border-radius:22px;overflow:hidden;background:radial-gradient(circle at 50% 45%,rgba(34,216,255,.12),transparent 36%),linear-gradient(145deg,#111d2a,#080c13);cursor:zoom-in}.media-stage:after{content:"اضغط لتكبير الصور";position:absolute;bottom:14px;right:14px;padding:7px 12px;border-radius:999px;background:rgba(2,6,10,.74);border:1px solid rgba(255,255,255,.12);font-size:12px;color:#d9f7ff}.main-img{width:82%;height:82%;object-fit:contain;filter:drop-shadow(0 30px 28px rgba(0,0,0,.55));transition:transform .45s cubic-bezier(.2,.8,.2,1)}.media-stage:hover .main-img{transform:scale(1.035) rotate(-1deg)}.thumbs{display:flex;gap:9px;margin-top:10px;overflow:auto;padding:3px}.thumb{flex:0 0 76px;height:76px;padding:4px;border-radius:14px;border:2px solid transparent;background:#101a26;cursor:pointer}.thumb.active{border-color:var(--cyan);box-shadow:0 0 0 3px rgba(34,216,255,.1)}.thumb img{width:100%;height:100%;object-fit:contain;border-radius:10px;background:#fff}
        .info{padding:10px 5px}.eyebrow{color:var(--cyan);font-weight:800}.info h1{font-size:clamp(30px,4vw,48px);line-height:1.15;margin:8px 0 12px}.tags{display:flex;gap:7px;flex-wrap:wrap}.tag{padding:7px 10px;background:#172432;border:1px solid rgba(255,255,255,.05);border-radius:9px;color:#c5d7e3}.price{font-size:36px;font-weight:900;margin:20px 0;background:linear-gradient(90deg,#fff,var(--cyan));-webkit-background-clip:text;color:transparent}.options-title{margin:0 0 10px;font-size:15px;color:#d9e6ee}.options{display:grid;gap:9px}.option{position:relative;display:grid;grid-template-columns:28px 1fr 1fr auto;gap:10px;align-items:center;padding:12px 14px;border:1px solid #284157;border-radius:15px;cursor:pointer;transition:.22s}.option input{position:absolute;opacity:0}.option:has(input:checked){border-color:var(--cyan);background:#102331;box-shadow:0 0 0 3px rgba(34,216,255,.08)}.option.sold{opacity:.4;cursor:not-allowed}.swatch{width:27px;height:27px;border-radius:50%;background:var(--swatch);border:2px solid rgba(255,255,255,.85);box-shadow:0 0 0 2px rgba(0,0,0,.55)}.variant-color{font-weight:800}.stock{font-size:12px;color:#68e7ac}.sold .stock{color:#ff8995}.buy{margin-top:18px;display:grid;grid-template-columns:1fr 1fr;gap:9px}.buy textarea,.buy button,.buy input{width:100%;border:1px solid #294156;background:#111c28;color:#fff;border-radius:13px;padding:13px}.buy textarea,.buy button,.buy #message{grid-column:1/-1}.buy button{border:0;background:linear-gradient(135deg,var(--cyan),var(--blue));color:#00131b;font-weight:900;font-size:17px;cursor:pointer}.buy button:hover{filter:brightness(1.08)}#message{min-height:24px;color:#7cecb4}.spec-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:26px 0}.spec{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:14px}.spec small{display:block;color:#7991a3;margin-bottom:5px}.related{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:50px}.related a{background:var(--panel);padding:12px;border:1px solid var(--line);border-radius:14px}.related img{width:100%;aspect-ratio:1;object-fit:contain;background:#fff;border-radius:10px}
        .lightbox{position:fixed;inset:0;z-index:100;display:none;background:rgba(0,3,8,.91);backdrop-filter:blur(10px);padding:24px}.lightbox.open{display:grid;grid-template-rows:1fr auto;animation:fade .2s ease}.lightbox-main{position:relative;display:grid;place-items:center;min-height:0}.lightbox-image{max-width:min(880px,82vw);max-height:78vh;object-fit:contain;filter:drop-shadow(0 30px 55px #000);animation:zoom .28s ease}.lightbox-close,.lightbox-arrow{position:absolute;border:1px solid rgba(255,255,255,.2);background:rgba(5,9,14,.78);color:#fff;display:grid;place-items:center;cursor:pointer}.lightbox-close{top:0;left:0;width:46px;height:46px;border-radius:50%;font-size:25px}.lightbox-arrow{top:50%;translate:0 -50%;width:52px;height:64px;border-radius:15px;font-size:32px}.lightbox-next{left:12px}.lightbox-prev{right:12px}.lightbox-thumbs{direction:ltr;display:flex;justify-content:center;gap:8px;overflow:auto;padding:10px}.lightbox-thumb{width:68px;height:68px;flex:0 0 68px;border:2px solid transparent;border-radius:10px;padding:3px;background:#111;cursor:pointer}.lightbox-thumb.active{border-color:var(--cyan)}.lightbox-thumb img{width:100%;height:100%;object-fit:contain;background:#fff;border-radius:7px}@keyframes fade{from{opacity:0}}@keyframes zoom{from{opacity:0;transform:scale(.9)}}
        @media(max-width:780px){html,body{width:100%;max-width:100%;overflow-x:hidden}.wrap{width:100%;max-width:none;padding-inline:10px}.top{width:100%;height:58px}.store-name{max-width:50%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product{display:block;width:100%;min-width:0;padding:10px;border-radius:20px}.gallery,.info{width:100%;min-width:0}.media-stage{width:100%;height:min(390px,92vw);padding:0;border-radius:16px}.main-img{width:82%;height:82%}.thumbs{width:100%;max-width:100%;padding-bottom:7px}.thumb{flex-basis:64px;height:64px}.info{padding:14px 2px 4px}.info h1{font-size:clamp(27px,9vw,36px)}.price{font-size:clamp(27px,9vw,36px);margin:14px 0}.option{width:100%;grid-template-columns:26px minmax(0,1fr) auto;padding:11px 9px;gap:7px}.option .ram{display:none}.variant-color{font-size:12px}.stock{font-size:10px}.buy{width:100%;grid-template-columns:1fr}.buy textarea,.buy button,.buy input{min-width:0}.spec-grid{width:100%;grid-template-columns:1fr 1fr;gap:7px}.spec{min-width:0;padding:11px;font-size:12px}.related{width:100%;grid-template-columns:1fr 1fr}.related a{min-width:0;padding:8px;font-size:11px}.lightbox{padding:8px}.lightbox-image{max-width:94vw;max-height:72vh}.lightbox-arrow{width:42px;height:54px}.lightbox-prev{right:2px}.lightbox-next{left:2px}}
        @media(max-width:380px){.wrap{padding-inline:7px}.product{padding:7px}.media-stage{height:88vw}.spec-grid{grid-template-columns:1fr}.related{gap:7px}}
        .lightbox{background:rgba(1,5,9,.68);backdrop-filter:blur(3px) saturate(.72)}
        .lightbox-image{background:transparent;filter:drop-shadow(0 34px 38px rgba(0,0,0,.72))}
    </style>
</head>
<body>
@php
    $attrs = $product->catalog_attributes ?? [];
    $resolveImage = fn ($path) => $path
        ? (\Illuminate\Support\Str::startsWith($path, ['http://','https://','storage/']) ? asset($path) : asset('storage/'.$path))
        : asset('images/1.jpg');
    $gallery = collect([$product->main_image])->merge($product->images->pluck('image'))->filter()->unique()->map($resolveImage)->values();
    if ($gallery->isEmpty()) $gallery = collect([asset('images/1.jpg')]);
@endphp
<div class="wrap">
    <header class="top"><a class="back" href="{{ route('electronics.store',$shop) }}">→ العودة للمتجر</a><span class="store-name">{{ $shop->name }}</span></header>
    <main class="product">
        <section class="gallery" aria-label="صور المنتج">
            <button class="media-stage" id="openGallery" type="button" aria-label="تكبير صور المنتج"><img class="main-img" id="mainImage" src="{{ $gallery->first() }}" alt="{{ $product->localized('name') }}"></button>
            <div class="thumbs">@foreach($gallery as $index=>$src)<button class="thumb {{ $index===0?'active':'' }}" type="button" data-index="{{ $index }}"><img src="{{ $src }}" alt="صورة {{ $index+1 }}"></button>@endforeach</div>
        </section>
        <section class="info">
            <div class="eyebrow">{{ data_get($attrs,'brand') }} · {{ data_get($attrs,'condition') }}</div>
            <h1>{{ $product->localized('name') }}</h1>
            <div class="tags"><span class="tag">{{ data_get($attrs,'network') }}</span><span class="tag">{{ data_get($attrs,'screen_size') }}</span><span class="tag">{{ data_get($attrs,'sim_type') }}</span></div>
            <div class="price" id="price">{{ number_format((float)($product->variants->where('quantity','>',0)->min('price') ?? $product->discount_price ?? $product->price),2) }} ₪</div>
            <h2 class="options-title">اختر التخزين واللون</h2>
            <div class="options">@foreach($product->variants as $variant)<label class="option {{ $variant->quantity<1?'sold':'' }}"><input type="radio" name="variant" value="{{ $variant->id }}" data-price="{{ (float)($variant->price??$product->discount_price??$product->price) }}" data-color-name="{{ $variant->color_name ?: $variant->color }}" @disabled($variant->quantity<1)><i class="swatch" style="--swatch:{{ $variant->color ?: '#777777' }}"></i><span><b>{{ $variant->storage ?: 'قياسي' }}</b><small class="ram">{{ $variant->ram ? ' · RAM '.$variant->ram : '' }}</small></span><span class="variant-color">{{ $variant->color_name ?: 'لون مخصص' }}</span><small class="stock">{{ $variant->quantity>0 ? $variant->quantity.' متوفر' : 'نفد' }}</small></label>@endforeach</div>
            <form class="buy" id="buyForm"><input name="customer_name" placeholder="الاسم الكامل" required><input name="customer_phone" placeholder="رقم الجوال" required><textarea name="customer_address" placeholder="عنوان التوصيل" required></textarea><textarea name="customer_notes" placeholder="ملاحظات اختيارية"></textarea><input type="number" name="qty" min="1" max="20" value="1"><button>تأكيد الطلب أونلاين</button><div id="message"></div></form>
        </section>
    </main>
    <section class="spec-grid">@foreach(['processor'=>'المعالج','battery'=>'البطارية','cameras'=>'الكاميرات','battery_health'=>'صحة البطارية','warranty_months'=>'الضمان بالأشهر','included_accessories'=>'الملحقات','condition_notes'=>'حالة الجهاز'] as $key=>$label)@if(filled(data_get($attrs,$key)))<div class="spec"><small>{{ $label }}</small>{{ is_array(data_get($attrs,$key))?implode('، ',data_get($attrs,$key)):data_get($attrs,$key) }}</div>@endif @endforeach</section>
    <h2>أجهزة مشابهة</h2><section class="related">@foreach($related as $item)<a href="{{ route('electronics.product',[$shop,$item]) }}"><img src="{{ $resolveImage($item->main_image) }}"><b>{{ $item->localized('name') }}</b></a>@endforeach</section>
</div>
<div class="lightbox" id="lightbox" role="dialog" aria-modal="true" aria-label="معرض صور المنتج"><div class="lightbox-main"><button class="lightbox-close" type="button" aria-label="إغلاق">×</button><button class="lightbox-arrow lightbox-prev" type="button" aria-label="الصورة السابقة">›</button><img class="lightbox-image" alt="{{ $product->localized('name') }}"><button class="lightbox-arrow lightbox-next" type="button" aria-label="الصورة التالية">‹</button></div><div class="lightbox-thumbs"></div></div>
<script>
const gallery=@json($gallery);let current=0;const transparentGallery=new Map(),mainImage=document.getElementById('mainImage'),lightbox=document.getElementById('lightbox'),lightboxImage=lightbox.querySelector('.lightbox-image'),lightboxThumbs=lightbox.querySelector('.lightbox-thumbs');
function removeEdgeBackground(src){if(transparentGallery.has(src))return transparentGallery.get(src);const job=new Promise(resolve=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>{try{const canvas=document.createElement('canvas'),limit=1400,scale=Math.min(1,limit/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height),pixels=frame.data,w=canvas.width,h=canvas.height,total=w*h,seen=new Uint8Array(total),queue=new Int32Array(total);let head=0,tail=0;const pale=index=>{const p=index*4,r=pixels[p],g=pixels[p+1],b=pixels[p+2];return r>226&&g>226&&b>226&&Math.max(r,g,b)-Math.min(r,g,b)<24};const add=index=>{if(index>=0&&index<total&&!seen[index]&&pale(index)){seen[index]=1;queue[tail++]=index}};for(let x=0;x<w;x++){add(x);add((h-1)*w+x)}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1)}while(head<tail){const index=queue[head++],x=index%w,p=index*4;pixels[p+3]=0;if(x>0)add(index-1);if(x<w-1)add(index+1);if(index>=w)add(index-w);if(index<total-w)add(index+w)}ctx.putImageData(frame,0,0);resolve(canvas.toDataURL('image/png'))}catch(error){resolve(src)}};image.onerror=()=>resolve(src);image.src=src});transparentGallery.set(src,job);return job}
async function selectImage(i){current=(i+gallery.length)%gallery.length;mainImage.src=gallery[current];document.querySelectorAll('.thumb').forEach((x,n)=>x.classList.toggle('active',n===current));lightboxImage.src=await removeEdgeBackground(gallery[current]);lightboxThumbs.querySelectorAll('.lightbox-thumb').forEach((x,n)=>x.classList.toggle('active',n===current))}
lightboxThumbs.innerHTML=gallery.map((src,i)=>`<button class="lightbox-thumb ${i===0?'active':''}" type="button" data-lightbox-index="${i}"><img src="${src}" alt="صورة ${i+1}"></button>`).join('');document.querySelectorAll('.thumb').forEach(x=>x.onclick=()=>selectImage(Number(x.dataset.index)));lightboxThumbs.onclick=e=>{const b=e.target.closest('[data-lightbox-index]');if(b)selectImage(Number(b.dataset.lightboxIndex))};document.getElementById('openGallery').onclick=()=>{selectImage(current);lightbox.classList.add('open');document.body.style.overflow='hidden'};function closeGallery(){lightbox.classList.remove('open');document.body.style.overflow=''}lightbox.querySelector('.lightbox-close').onclick=closeGallery;lightbox.querySelector('.lightbox-next').onclick=()=>selectImage(current+1);lightbox.querySelector('.lightbox-prev').onclick=()=>selectImage(current-1);lightbox.onclick=e=>{if(e.target===lightbox)closeGallery()};addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')closeGallery();if(e.key==='ArrowLeft')selectImage(current+1);if(e.key==='ArrowRight')selectImage(current-1)});
document.querySelectorAll('[name=variant]').forEach(v=>v.onchange=()=>document.getElementById('price').textContent=Number(v.dataset.price).toFixed(2)+' ₪');document.getElementById('buyForm').onsubmit=async e=>{e.preventDefault();const variant=document.querySelector('[name=variant]:checked'),message=document.getElementById('message');if(!variant){message.textContent='اختر التخزين واللون أولاً.';return}const fd=new FormData(e.currentTarget),payload={customer_name:fd.get('customer_name'),customer_phone:fd.get('customer_phone'),customer_address:fd.get('customer_address'),customer_notes:fd.get('customer_notes'),items:[{variant_id:Number(variant.value),qty:Number(fd.get('qty'))}]};message.textContent='جارٍ تسجيل الطلب...';const res=await fetch(@json(route('electronics.orders.store',$shop)),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:JSON.stringify(payload)});const data=await res.json();message.textContent=res.ok?'تم تسجيل طلبك: '+data.order_number+' — اللون: '+variant.dataset.colorName:(data.message||'تعذر تسجيل الطلب');if(res.ok)e.currentTarget.reset()};
</script>
</body></html>
